### PR TITLE
Thread list

### PR DESCRIPTION
**Pull request by nickstenning**
This set of changes attempts to make the thread directive easier to understand by turning it into a more normal angular directive that has a consistent template.

In order to do this, a new directive, `threadList`, is introduced, which is responsible for rendering the top-level list of cards, leaving the `thread` directive responsible solely for a single annotation and its replies.

### CODE REVIEW

**Comment by aron** [comment]
Wonderful :pineapple:

**Comment by tilgovi** [comment]
I'm a fan of some of it. I'm not a fan of the rest.

I don't like the way you need to use the recursive service. I have a recursive directive that I think is far more sensible that I have shared before in a plunk.

I don't like the separation between thread and thread list. A list of things doesn't need its own directive, to me. The things themselves do.

The number of attributes on the thread list directive is hideous, especially when some are just about passing context down the DOM which is mostly about style. CSS could be a much more direct route to the same.

How can I help?

**Comment by tilgovi** [comment]
Check out this plunk and tell me if you'd rather have this recursive directive and do much more in CSS.

http://plnkr.co/edit/MSiwnDFD81HAOXWvQWIM?p=info

- Collapsing is just a directive that wraps a container with a collapser element and sets CSS classes (this could expose attributes, instead, if we want to be more directive-y).
- The actual style of the collapsed state is pure CSS.
- Recursion is an unobtrusive directive. You just drop it in two places within a template and boom.

In our case, rather than the anonymous template showing tasks in this example, we would have our annotation directive as the thing inside the thread. We could use ng-include to include a thread.html, or we could break up viewer.html and stream.html and things might just be pretty clean.

I don't think there's need for all the properties on the thread list, since they do just fine in viewer.html. If we separated viewer and stream, a few would go away. We could break up the annotation itself if we wanted to dodge the extra attributes that are there for `isEmbedded`.

I do believe that I'd rather have:

- recursive directive
- annotation directive
- collapse directive

Than have much more:

- thread directive
- recursion service
- annotation directive
- thread-list directive

It seems like the thread-list directive is just holding a bunch of state that differentiates between the stream and the viewer when that could just be in separate templates.

We're still passing a bunch of nastiness around to deal with the fact that we don't have a real collapse directive that could be easily added or withheld from aforementioned templates.

**Comment by tilgovi** [comment]
Here's some of what I was doing when I cut myself off on thread stuff last: https://github.com/tilgovi/h/compare/1803-no-standalone-parents

I think we can leverage CSS better, drastically simplify it. In my version, there's a collapser at the left of the top level name (rather than just replies) which is nice and consistent, but if we incorporate my plunk work then it becomes a simple matter of using it (or not) on the reply elements.

There's a bunch of other simplifications here if we want to make them, I just lost track of everything because there's so much.

What you've done here, though, I think moves in the wrong direction. Rather than create composable pieces, you've swept lots of disparate things under a new, overly chunky interface. I would like to factor things better rather than sweep them under the proverbial rug.

**Comment by gergely-ujvari** [comment]
Somme comments:
Separating the thread and the stream templates is a very good idea. If that can simplify the controller all the way better. I'm imagining that as we'll discuss the future of the stream other changes will emerge too between our viewer and the stream templates.

If we really can separate orthogonal features (like collapsed) into directives that is a very good way to go.

And although the interface is huge indeed, the PR description says it makes things easier to understand and it really does that. So I like that part very much, and suggests merging it, and opening new smaller separate PRs for simplifying this directive and introducing all the goodies @tilgovi suggested. 

Otherwise we'll end up with a huge PR with many-many refactorings.

**Comment by nickstenning** [comment]
First things first: I think we all agree on where we want to go. The only difference is whether we want to go there all at once or whether we can get there in little steps.

This pull request doesn't add any features, it doesn't remove any code, it doesn't improve any user experience. It just makes a few things explicit that were previously implicit. For example, when you say:

> The number of attributes on the thread list directive is hideous

I couldn't agree more. But all I'm doing is making explicit the shared mutable state that is currently implicit. Sure, I haven't made it much less messy, but I have made it easier to reason about what's going on. Also, it's not true that the `threadList` directive is just doing what `ng-repeat` should be doing. It's also providing an isolated scope, meaning that you can look at exactly one place and know everything that is in the current namespace. I like that.

I've taken a look at the `1803-no-standalone-parents` branch, and I like plenty that I see. You'll note that the followup pull request to this one (#1943) makes some of the same simplifications to the thread directive.

But it also changes some behaviour and (in my opinion) breaks some behaviour: to pick one example of each:

- editors disappear when a thread collapses
- replies don't "uncollapse" when they match a search

I would encourage you to look at this pull request in combination with the followup #1943. I don't believe they rule out moving forwards to the solutions you've suggested, Randall. They do at least increase the test coverage of some important parts of the thread directive and make it much easier to reason about what's going on.

I think this and #1943 are pretty reasonable first steps to doing exactly what you want to do.

**Comment by csillag** [comment]
fwiw, I think what @nickstenning is trying to do here makes total sense, and it's worth to do this, even without resolving all the problems mentioned by @tilgovi.

**Comment by tilgovi** [comment]
@nickstenning after talking with you about this today, what do you think if I simply replace the recursive part with my recursive directive from my plunk?

I know you said you think it may be too clever and you don't know if you could predict how it affects scope, but it's actually really easy. It doesn't create a new scope, isolated or otherwise. The entire recursion happens irrespective of scope. The children only have a new scope if the template uses other directives that cause a new scope to be created before or at the point of recursion.

I think my directive is also superior because it does less compilation. Both depend upon deferring some work until linking so that the base case has a chance to cull the recursive elements (such as an empty repeat). However, the helper service breaks the compilation and defers it until link time, causing causing compilation at every recursive call. My directive lets angular do the compilation once using the transclude attribute and makes the transclude linking function available to the recursion via controller inheritance.

They differ in that the helper service lets you make a directive recursive while mine only makes a template recursive and cannot be used at the same point as another directive that has a template. However, that also means that mine is more isolated in some sense.

**Comment by tilgovi** [comment]
I've just read this again and I've decided that I don't think this is helpful. We should try separating the viewer and the streamer templates instead. I think it will simplify enough of the attributes on the thread `li`, especially for the stream template. I think I actually prefer having the attributes in the viewer template anyway. If there were some behavior (business or DOM) associated with the thread-list, or some interpretation of the attribute values, it would make sense to put them in a directive. Otherwise, this just introduces a layer of indirection where the thread list re-labels a bunch of scope keys.

**Comment by nickstenning** [comment]
> Otherwise, this just introduces a layer of indirection where the thread list re-labels a bunch of scope keys.

Correct. This layer of indirection is intended to make the code easier to understand by:

- reducing the number of contexts in which the thread directive is used from three to two
- limiting the amount of the parent scope that is exposed to the thread list, and thus relying less on shared global state, which is often hard to reason about
- turning the thread directive into a "normal" directive with a template rather than one that relies on (IMO) abuse of `ng-include`

If you think this change makes things harder to understand, or slower, or in some other way worse, it would help me if I could understand how or why. At the moment I don't. Perhaps I'm being slow.

In particular, I'm a little disappointed you've closed this when @aron, @csillag and @gergely-ujvari have all voiced their support for it. I'm happy to make changes in order to get us all agreed one way or the other, but unilaterally closing the discussion doesn't seem conducive to forward progress. 

Lastly, this is currently a prerequisite for #1943. Do you not want any of the changes in that PR either...?

**Comment by tilgovi** [comment]
Definitely removing the ng-include abuse is a goal I have. It's there as a hack for the recursion. The solution in my plunk doesn't need that.

I don't think this really reduces the use of global state, it just makes it look pretty by rewriting it all as thread-list-*. Nor is that state really global, since much of it is local to the sidebar viewer. Moving the selection state and focus stuff into the ViewerController would clean up the AppController and mean that this state is initialized, managed and used by a single scope/template. The search template wouldn't need these.

The service you've used for recursion I would expect to be slower because it calls the compile service at each step rather than just once.

As for the other pull request, I haven't looked because it said this was a prerequisite. If there are good ideas there I want them but if it builds on this I do not. There is nothing in this pull request I want.

**Comment by tilgovi** [comment]
If it wasn't totally clear, what I'm saying is the global-ness of a lot of this state comes from it being set and managed by the AppController when it should be local to the ViewerController and it's template. Passing it all through a new directive layer makes the viewer template superficially prettier but doesn't actually improve anything to me and even removes some of it farther from where it's managed.

As far as I can tell, your own stated goals are not well met by this PR, but they would be very well met by moving selection and focus into the ViewerController and splitting the viewer and search templates. The removal of ng-include could be accomplished with my recursion directive.

**Pull request closed without merging**
