### PR TITLE
Unbreak fuzzy

### LINKED ISSUE #2013: Strategy 'two-phase fuzzy' has thrown an error. ReferenceError: diff_match_patch is not defined
Seen with Prod extension v0.3.2.1724

To reproduce:
1. Open https://en.wikipedia.org/wiki/Main_Page
2. Activate our extension on the page
3. Check console logs

Result:
```
 Strategy 'two-phase fuzzy' has thrown an error. ReferenceError: diff_match_patch is not defined
    at new DTM_DMPMatcher (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:6:21900)
    at DomTextMatcher.window.DomTextMatcher.DomTextMatcher.ensureDMP (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:5:31587)
    at DomTextMatcher.window.DomTextMatcher.DomTextMatcher.searchFuzzyWithContext (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:5:27224)
    at FuzzyTextAnchors.Annotator.Plugin.FuzzyTextAnchors.FuzzyTextAnchors.twoPhaseFuzzyMatching (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:2:5094)
    at EnhancedAnchoring.bind (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:2:3052)
    at EnhancedAnchoring.Annotator.Plugin.EnhancedAnchoring.EnhancedAnchoring.createAnchor (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:1:31418)
    at Host.Annotator.setupAnnotation (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:1:10053)
    at Annotator.loadAnnotations.loader (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/vendor/annotator.min.js?78a3f6c6:1:25188)
    at Host.Annotator.loadAnnotations (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/vendor/annotator.min.js?78a3f6c6:1:25368)
    at Host.Annotator.Plugin.EnhancedAnchoring.EnhancedAnchoring.pluginInit.Annotator.loadAnnotations (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:1:31086)
hypothesis.min.js?5750b1df:1 Strategy 'one-phase fuzzy' has thrown an error. ReferenceError: diff_match_patch is not defined
    at new DTM_DMPMatcher (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:6:21900)
    at DomTextMatcher.window.DomTextMatcher.DomTextMatcher.ensureDMP (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:5:31587)
    at DomTextMatcher.window.DomTextMatcher.DomTextMatcher.searchFuzzy (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:5:26334)
    at FuzzyTextAnchors.Annotator.Plugin.FuzzyTextAnchors.FuzzyTextAnchors.fuzzyMatching (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:2:6244)
    at EnhancedAnchoring.bind (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:2:3052)
    at EnhancedAnchoring.Annotator.Plugin.EnhancedAnchoring.EnhancedAnchoring.createAnchor (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:1:31418)
    at Host.Annotator.setupAnnotation (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:1:10053)
    at Annotator.loadAnnotations.loader (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/vendor/annotator.min.js?78a3f6c6:1:25188)
    at Host.Annotator.loadAnnotations (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/vendor/annotator.min.js?78a3f6c6:1:25368)
    at Host.Annotator.Plugin.EnhancedAnchoring.EnhancedAnchoring.pluginInit.Annotator.loadAnnotations (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/public/scripts/hypothesis.min.js?5750b1df:1:31086)
```

### PR DESCRIPTION
**Pull request by csillag**
This fixes #2013 by re-adding the diff-match-patch library to our bundles.

### CODE REVIEW

**Comment by nickstenning** [comment]
This should already be handled by [these lines in `package.json`](https://github.com/hypothesis/h/blob/616ffa9819f0a22b7c82828e8d97be146887c10e/package.json#L57-L60). If they're not working we should work out why rather than adding the dependency to `assets.yaml`.

**Comment by csillag** [comment]
Oh, I wasn't aware of that location. OK, will continue to debug it from there...

**Comment by tilgovi** [comment]
Should I close this then?

**Comment by csillag** [comment]
No, don't close it. I'll just push the correct fix here later.

**Comment by tilgovi** [comment]
Oh, I see what's going on. Just read #2013.

**Comment by tilgovi** [comment]
Closing after cd87c2cab4017cc109ff0d4f8652db48538240eb.

**Pull request closed without merging**
