### PR TITLE
Limit what admins can do

### LINKED ISSUE #2422: Restrict what admins can do
Currently on master admins can do absolutely everything (e.g. edit and delete other people's annotations) which is too much.

### PR DESCRIPTION
**Pull request by seanh**
Fixes #2422

### CODE REVIEW

**Comment by seanh** [comment]
@tilgovi

**Comment by tilgovi** [comment]
Totally fine but I'd call it `AdminResource`. The context for a request is a resource, the resource itself is just a resource, not a "context resource".

**Comment by seanh** [comment]
@tilgovi Done

**Comment by tilgovi** [comment]
:rocket:

**Pull request merged**
