### PR TITLE
Upgrade JS dependencies

### PR DESCRIPTION
**Pull request by esanzgar**
On the first commit, I updated all the dependencies to the latest version. There are still some dependencies that are old and unmaintained.

On the second commit, I made 'ChromeHeadless' to run the test code, instead of 'PhantomJS';

### CODE REVIEW

**Comment by robertknight** [comment]
@esanzgar - Since there ended up being quite a lot of changes in this PR I think we need to break it into several stages. I suggest the first of these is to update our browser baseline as that will enable us to remove obsolete polyfills and workarounds for old browsers. I tried to do this in https://github.com/hypothesis/h/pull/6615 but then discovered that npm (I'm using v7.10) tried to rewrite the lockfile to a newer version when any dependency changes were made. As a result I split the lockfile update into https://github.com/hypothesis/h/pull/6616. Once those PRs are merged, it should then be possible to rebase this PR and apply the remaining updates.

**Comment by robertknight** [comment]
Hi @esanzgar - I suggest that we merge https://github.com/hypothesis/h/pull/6615 before updating dependencies, as it removes some dependencies and reduces the total amount of work that we need to do.

**Comment by robertknight** [comment]
I have opened up a [follow-up PR](https://github.com/hypothesis/h/pull/6638) to #6615 which switches the frontend tests to run in Chrome, fixing failures in several tests along the way, and removes polyfills that were only needed in PhantomJS.

Once that has landed, it should be possible to upgrade the remaining dependencies more easily.

**Comment by esanzgar** [comment]
@robertknight break out this large task into smaller and simpler steps that have enable to remove dependencies no needed anymore.

**Pull request closed without merging**
