### PR TITLE
[WIP] Bring back padded scrolling

### LINKED ISSUE #1776: Bring back the padded scrolling
When we scroll to a highlight (either by clicking an up/down arrow tab, or clicking an annotation (as fixed since #1634)), we scroll _just_ far enough to get the highlighted text into view. However, at least at the top of the screen, there are often bars covering a lines of the text, like for example on [Medium](https://medium.com/@jedsundwall/how-do-we-stay-sane-57b4078974fb). This makes me search every time where the highlight is until I discover it was just out of sight.

I suggest we scroll a little further so that it the highlight is not on the edge of the page. Maybe we want to get it exactly in the middle of the window?

### PR DESCRIPTION
**Pull request by csillag**
This resurrects the padded scrolling feature, which would make direct linking look a lot better.

This version that adds a change to the upstream (abandoned) jQuery scrollIntoView plugin.
I am just putting this here as a baseline; see the previous discussion at #1899.

Fixes #1776.

### CODE REVIEW

**Comment by csillag** [comment]
Oh - this is Chrome-only, for now. 
FF doesn't add any padding, for some reason.

**Comment by csillag** [comment]
> FF doesn't add any padding, for some reason.

Fixed that.

**Comment by csillag** [comment]
> > FF doesn't add any padding, for some reason.

> Fixed that.

Scratch that. FF still does the wrong thing :(

**Comment by nickstenning** [comment]
Sorry, I'm still as vehemently opposed to patching 3rd-party libraries as I was last time around. You need to either move the code out of `vendor/` (thus breaking the assumption that it comes, untouched, from another source) or find a way of augmenting the behaviour of the plugin without patching it. I'd prefer the latter.

**Comment by csillag** [comment]
Yep, this is why I wrote that

> I am just putting this here as a baseline

and also added the WIP thread. My plan is to refactor this is whatever way necessary, and merge it after that.

**Comment by tilgovi** [comment]
Let's re-open this when we have a solution that doesn't involve modifying the vendor libs.

**Pull request closed without merging**
