### PR TITLE
Fix tag search

### LINKED ISSUE #1879: Hashtags in tags break stream searches
This doesn't find the associated tags:
https://hypothes.is/stream?q=tag:%27#teachtheweb'

Here's what the annotation looks like:

screen shot 2015-01-22 at 1 39 34 pm

### PR DESCRIPTION
**Pull request by gergely-ujvari**
When we began using the search api instead of the websocket, we've broken the 'tag' search.
This PR fixes is.

Fix #1879

### CODE REVIEW

**Comment by dwhly** [comment]
Thanks @gergely-ujvari!

**Comment by aron** [comment]
@gergely-ujvari :thumbsup: I also noticed that we don't escape pound symbols in tags so I added that too.

**Comment by dwhly** [comment]
Was this deployed?  Still broken live. https://hypothes.is/stream?q=tag:%27teachtheweb%27

**Comment by gergely-ujvari** [comment]
No, this was definitely not deployed to prod.

**Comment by edrex** [comment]
I noticed extraneous %27s in q=tag URLs, and ended up here. Is that fixed in this pull?

**Comment by tilgovi** [comment]
No. If you can demonstrate what you're seeing in a new issue, that'd be helpful. The `%27` is a URL-encoded single quote. I would expect the browser to show it as a single quote.

**Comment by edrex** [comment]
i just wonder why it's being included in the URL. doesn't seem to be needed as a delimiter since the tag is already URL encoded. looks ugly.

**Pull request merged**
