### PR TITLE
Remove use of elasticseach6 feature flags

### PR DESCRIPTION
**Pull request by hmstepanek**
This is part of es6 transition cleanup https://github.com/hypothesis/product-backlog/issues/608.  This will remove using elasticsearch6 only when feature flags are enabled and make the switch permanent.

### CODE REVIEW

**Comment by robertknight** [comment]
Just to recap the high level plan here, you are intending to:

1. Remove all the code paths that use the `h.search.client.Client` for Elasticsearch 1 (ie. `request.es`, `es_client`), in this PR.
2. Rename `request.es6` => `request.es`, `es6_client` => `es_client` subsequently?

This seems reasonable to me. I thought about making `request.es` the ES6 client instead and then just removing the `request.es6` code path but the way you've done it here is probably a bit more straightforward.

**Comment by hmstepanek** [comment]
Yes, remove the usage of the feature flags and remove any calls to request.es. Note not _all_ calls to request.es are removed in this PR. Only the ones surrounding the feature flags. I'm working on another PR for removing the rest of them. I also noticed (while I was in the processes of doing that) that there are still some places where we are using es1 and only es1 in the code so we should prob discuss what to do about those.

**Comment by hmstepanek** [comment]
It failed functional testing on CI last night so that’s why I marked in WIP. Not sure what’s going on there.

**Comment by hmstepanek** [comment]
I made a note about the es6 flag in the cleanup task list so we don't forget.

**Pull request merged**
