### PR TITLE
Remove vendored assets: install from NPM

### PR DESCRIPTION
**Pull request by nickstenning**
Replaces our vendored dependencies with dependencies on packages
installed from NPM. This makes it substantially easier to find out
what versions of 3rd-party packages are installed, and substantially
easier to upgrade them as and when necessary.

Libraries have been installed pinned at the version available on NPM
nearest that installed in the repository. This means:

- angular remains v1.2.28
- angular-animate was upgraded from v1.2.25 -> v1.2.28
- angular-resource was upgraded from v1.2.25 -> v1.2.28
- angular-route was upgraded from v1.2.25 -> v1.2.28
- angulartics remains v0.17.2
- bootstrap remains v3.3.5
- jquery remains v1.11.1
- jstimezonedetect remains v1.0.5
- moment remains v2.5.0
- moment-timezone remains v0.0.1
- ng-tags-input remains v2.2.0

Unfortunately, the following modules don't appear to be available on NPM
and so remain in the repository:

- angular-bootstrap
- angular-sanitize
- angular-toastr (at a version early enough)

### CODE REVIEW

**Comment by nickstenning** [comment]
One of these days I am going to take the extension builds to the back of the building with a crowbar...

**Comment by tilgovi** [comment]
Or, just, to another repo :)

**Comment by nickstenning** [comment]
Or that :)

**Comment by nickstenning** [comment]
I'd strongly recommend actually checking this branch out and poking around to see if I've missed anything or if anything is broken that I haven't noticed.

**Comment by tilgovi** [comment]
This looks great.

**Comment by tilgovi** [comment]
It appears to work.

**Comment by tilgovi** [comment]
Thanks, Nick.

**Pull request merged**
