### PR TITLE
Remove some test duplication

### PR DESCRIPTION
**Pull request by seanh**

### CODE REVIEW

**Comment by lyzadanger** [comment]
My $.02 : Given the codecov report goodness, I always love me a red PR!

**Comment by seanh** [comment]
I think codecov might be drunk already

**Comment by seanh** [comment]
I'm glad you're doing mutation testing!

> There isn't a test to validate that if publish is None it doesn't attempt to publish.

Good point. I also wonder if publish every really _is_ `None` in practice. If not it could be made a required argument which would simplify things.

_This_ particular pull request is just tidying up the issue with the tests not using the `service` fixture though, so I think I'd like to merge this and deal with the publish issue separately if that's okay?

> If you comment out self.session.add(group) all the tests still pass ... if it's an open group (aka: a creator is not added as a member) and for some reason the self.session.add(group) doesn't get called (aka a dev accidentally deletes it or something) group.id will not get populated

I think it's actually worse than that - if `creator` was `None` and `add()` didn't get called then I don't think the group would be added to the DB and saved at all!

I think you're right that there should be tests that the new group is actually added to the DB in various circumstances (private group, open group, publish or no publish). I guess the way to do this would be for the tests to query the DB to retrieve the group, instead of just getting it from the method's return value.

Also, do we ever create groups with no creators in practice? Again it might simplify things to just enforce that the creator must always exist.

Again, I'd like to get this one merged and deal with that in a separate pr.

Thanks for finding these issues!

**Comment by seanh** [comment]
> > I guess the way to do this would be for the tests to query the DB to retrieve the group, instead of just getting it from the method's return value.
> 
> I looked into this briefly on Friday. I think it's possible to do this by adding handlers to catch when a transaction happens and when a flush happens. http://docs.sqlalchemy.org/en/latest/orm/events.html

I'd recommend tests maybe treating the database and sqlalchemy as a black box. If you call `service.create()` and it _doesn't_ `add()` the group to the DB, then I think if the test queries the DB (`db_session.query(...)`) with a query that should retrieve the group, it'll find nothing instead.

Either way, @hmstepanek do you want to have a go at a pull request to fix this test issue? Make it so that removing the `add()` causes at least one test to fail.

**Pull request merged**
