### PR TITLE
[wip] Add jshint to `make lint`

### PR DESCRIPTION
**Pull request by seanh**

### CODE REVIEW

**Comment by seanh** [comment]
Lots of jshint errors: <https://github.com/hypothesis/h/pull/2173> I think some of the globals and environment options I added in jshintrc are too broad as well, they should only apply to some of the files not all.

**Comment by nickstenning** [comment]
I'm not going to advocate doing a massive cleanup on these just to get the tests passing. In my experience that's a great way to break stuff.

For this and #2172, I think we should look into a way of computing lint/health/etc, without necessarily failing the build.

**Comment by nickstenning** [comment]
For example, we can configure [Landscape](https://landscape.io) to comment on pull requests that make things worse. I presume that we can do the same for JavaScript somehow.

**Comment by nickstenning** [comment]
One option worth looking into: https://houndci.com/

**Comment by nickstenning** [comment]
Closing in favour of #2246.

**Comment by tilgovi** [comment]
Keep the branch around or delete?

**Comment by seanh** [comment]
Deleted. You can restore pull request branches on GitHub, forever as far as I can see.

**Pull request closed without merging**
