### PR TITLE
Add pyramid_redis_sessions dev dependency

### PR DESCRIPTION
**Pull request by seanh**
Needed to build the Chrome extension with production.ini

### CODE REVIEW

**Comment by tilgovi** [comment]
I'm not sure I think that makes it a dev dependency :-/.

It would certainly be better if the extension build process didn't require the session plugin to be loaded.

**Comment by nickstenning** [comment]
+1 -- I don't think this is a dev dependency, we should rather do one of:

1. add `pip install -r requirements.txt` to the documentation for building a prod extension
2. remove the requirement to spin up the entire application in order to build the extension (more work, but ultimately preferable, I think)

**Comment by seanh** [comment]
I hadn't even noticed we had a requirements.txt file. When do we use it? (Grepping for requirements.txt gives no results, and afaik we don't use it in the install process)

**Comment by seanh** [comment]
> add pip install -r requirements.txt to the documentation for building a prod extension

I'll probably do this just because A) I want the docs for building the Chrome extension to work without error and B) I want to get past this quickly and work on nipsa instead

**Comment by tilgovi** [comment]
Please update the docs, that'd be awesome.

requirements.txt is used in our Dockerfile

It's also used automatically by PaaS systems likes Heroku and Dokku.

**Comment by seanh** [comment]
It's gone into the docs pr

**Pull request closed without merging**
