### PR TITLE
Postgres Write 1/4: Add postgres_write feature flag

### PR DESCRIPTION
**Pull request by seanh**

### CODE REVIEW

**Comment by seanh** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0xedAaiS&#x2F;282-postgres-write-annotation-creates-and-updates-to-postgres-when-the-postgres-write-feature-flag-is-on"> Postgres: write annotation creates and updates to postgres when the postgres_write feature flag is on</a>

**Comment by chdorner** [comment]
This is obviously looking good, I just thought we'll wait with merging any of these 4 pull requests until we're all happy?

**Comment by seanh** [comment]
Yep, sounds good to me

**Comment by seanh** [comment]
Let's hold off on merging this until direct linking is released.

Then I think it would be good to get this one merged before we merge 3/3 and 4/4, it'll just make 3/3 and 4/4 easier to test

**Comment by seanh** [comment]
Closing in favor of https://github.com/hypothesis/h/pull/3171

**Pull request closed without merging**
