### PR TITLE
Snap the sidebar closed as well as open

### LINKED ISSUE #2162: Sidebar is not marked as closed when hidden by resizing
Follow-up to #2149, which left the sidebar sometimes in a state where two clicks are needed to open it.

This can be fixed by checking the size at gesture end and toggling the sidebar as "closed" when it is less than the "show" threshold.

### PR DESCRIPTION
**Pull request by tilgovi**
Close #2162

### CODE REVIEW

**Comment by judell** [comment]
Thanks!

**Comment by nickstenning** [comment]
Worth adding some tests for this behaviour?

**Comment by tilgovi** [comment]
I'll take a quick look. I'm always shy about testing UI because I haven't
done it that much, but I'll see what might be decomposed and mocked.

**Comment by tilgovi** [comment]
@nickstenning totally forgot I had added tests for these gestures already and the test change was tiny and easy.

**Comment by tilgovi** [comment]
Dead simple and done. I'll merge it myself.

**Pull request merged**
