### PR TITLE
Keep JWZ and threading idTables in sync

### LINKED ISSUE #2182: Cannot press cancel on annotation replies in the stream
Create an annotation, go to the stream.  Click "reply".  Now click cancel.  Nothing happens.

Console message:

TypeError: Cannot read property 'children' of undefined
    at Threading.module.exports.Threading.annotationDeleted (app.min.js?36c6163a:3)
    at app.min.js?36c6163a:3
    at Scope.$emit (angular.min.js?5edec867:5)
    at revert (app.min.js?36c6163a:2)
    at angular.min.js?5edec867:4
    at callback (angular.min.js?5edec867:6)
    at Scope.$eval (angular.min.js?5edec867:5)
    at Scope.$apply (angular.min.js?5edec867:5)
    at HTMLButtonElement.<anonymous> (angular.min.js?5edec867:6)
    at HTMLButtonElement.jQuery.event.dispatch (jquery.min.js?74d54652:2)

### PR DESCRIPTION
**Pull request by gergely-ujvari**
When StreamController creates a new idTable, it also gives this new idTable to the threading service. 
Before this fix they were out of Sync.

Fix #2182

### CODE REVIEW

**Comment by csillag** [comment]
LGTM.

**Comment by csillag** [comment]
Travis failed with this message:

> Your test run exceeded 50 minutes.
> One possible solution is to split up your test run.

This might be caused by the temporary spike in load (see [here](http://www.traviscistatus.com/incidents/yk24wrkb4082)), so I don't think we need to worry about this, for now.

**Comment by gergely-ujvari** [comment]
I've restarted the travis build.

**Comment by csillag** [comment]
> I've restarted the travis build.

I think it will timeout again.

**Comment by tilgovi** [comment]
I would like you to explain to me why this is correct.

Looking at the code for JWZ, `idTable` is a getter exposing a constructor-scoped variable that `createIdTable` assgins to (without the `var` keyword).

I don't understand how it could ever be out of sync, unless we assign to it elsewhere.

**Comment by tilgovi** [comment]
In other words, if I'm understanding the code correctly, this PR is creating the same problem it's trying to solve.

**Comment by tilgovi** [comment]
See here: https://github.com/hypothesis/h/pull/2199

**Comment by gergely-ujvari** [comment]
@tilgovi: The problem lies around  [extending](https://github.com/hypothesis/h/blob/master/h/static/scripts/threading.coffee#L10) is not real inheritance. Checking #2199

**Comment by gergely-ujvari** [comment]
closing in favor of #2199

**Pull request closed without merging**
