### PR TITLE
Add docs for serving ssl in development

### PR DESCRIPTION
**Pull request by seanh**

### CODE REVIEW

**Comment by nickstenning** [comment]
Great. Could you rebase this into a single commit?

**Comment by seanh** [comment]
Rebased here: https://github.com/hypothesis/h/pull/2154

**Comment by nickstenning** [comment]
You know you can just force push the branch, right?

**Comment by seanh** [comment]
Isn't that bad though? ;)

**Comment by nickstenning** [comment]
In a word: no.

**Comment by tilgovi** [comment]
@seanh it's slightly dangerous when you have collaborators whose changes you might clobber (look before you force!). Feature branches usually have more-or-less a single owner, though, so there's low risk.

**Comment by seanh** [comment]
My worry was the it causes confusion for anyone else that has a tracking branch, yeah. If I rebase it then they try to pull or push they'll get a mess. There was a time when people in `#git` would tell you off very sternly if you mentioned doing this. But they're a frowny bunch in there. <http://git-scm.com/book/en/v2/Git-Branching-Rebasing#The-Perils-of-Rebasing> ("people will hate you, and you’ll be scorned by friends and family").

But it is convenient though so alright - force pushing single-developer feature branches it is then.

**Pull request closed without merging**
