### PR TITLE
[WIP] Load ascendant annotations for replies in initial stream search

### LINKED ISSUE #1916: Too many message not available on stream
When I open a stream page I often see too many "message not available" cards with some replies.
This is very confusing for a normal user and he/she may believe that the stream is not working.
bad_stream
 
The cause of this error that our search requests are sorted (and sadly this is "hardcoded" in the backend) by the updated field descending.

This means that the replies (as they were created later then the parent) are retrieved before their parents thus resulting in "Message not available" cards with replies that you can open. 
Of course scrolling down solves this as by the inf. scrolling feature the parents will be loaded eventually.

We have to seriously improve this.

### PR DESCRIPTION
**Pull request by gergely-ujvari**
Also do not show threads without message

Fix #1916

### CODE REVIEW

**Comment by gergely-ujvari** [comment]
Okay, so this is a solution for #1916. Before adding the necessary test, I'd love to hear some comments from others.

**Comment by nickstenning** [comment]
First a minor niggle: I think `ancestor` would probably be better word than `ascendant`.

Second, it looks like we're going to be making one HTTP request per missing ancestor. I'm not sure that's a good idea.

**Comment by nickstenning** [comment]
Other than that it looks fine. I do have worries about the user's interpretation of the stream -- you're now going to be loading a top-level card that could have been written *ages* ago, and displaying it in what is apparently a stream of recent annotations.

But I guess that's a broader concern that doesn't fit within the context of fixing #1916.

**Comment by gergely-ujvari** [comment]
Ok, I'm now using ancestors.
About HTTP request, I'd love to do it in one step but our search api is not working for a list of ids very well.
So i.e this request is working: https://api.hypothes.is/search?text=['test','whether']
But this isn't: https://api.hypothes.is/search?id=['gZpaGTfPS5q2v7BSqiY6HA','RMYcApQdQja3aMNtTe1CrA']
although the ids exists: https://hypothes.is/a/gZpaGTfPS5q2v7BSqiY6HA,  https://hypothes.is/a/RMYcApQdQja3aMNtTe1CrA

**Comment by gergely-ujvari** [comment]
And yes, you're right about the purpose of the stream, but that is really a different issue. Here I'm just trying to quick-fix (bandage) this apparent problem.

**Comment by tilgovi** [comment]
I thought we indexed the references field with the prefix hierarchy analysis so that searching on the references field for the root id will give you the whole conversation.

**Comment by gergely-ujvari** [comment]
Yes, you're right. However it doesn't seem to be working for me. The annotations arrive but the cards are not refreshed.
I've created this branch to demonstrate: https://github.com/hypothesis/h/tree/1916-stream-message-not-available-2

To be on the same page for testing, create 10 new replies for a root annotation and check the stream page with the two branches.
With this branch you'll see the root annotations and all replies, but with the second branch you'll only see a message not available card.
I've checked the network tab, the annotations do arrive from the backend and the annotationMapper receives them but for some reason the loadAnnotations function doesn't refresh the cards. 

Am I missing something very trivial here?

**Comment by tilgovi** [comment]
Looking at models.py right now:

- We have a 'thread' analyzer
- The 'thread' analyzer is used by the 'thread' field

But:

- We don't have a thread field

I think a long time ago I might have been persisting the references field
as a /-separated string in the thread field, but that's long gone.

So this isn't a thing anymore.

**Comment by gergely-ujvari** [comment]
Oh, I see..

**Comment by gergely-ujvari** [comment]
Okay, with that in mind, now https://github.com/hypothesis/h/tree/1916-stream-message-not-available-2 is working, and it uses less number of requests.

**Comment by tilgovi** [comment]
This changes the behavior of the stream so that replies do not appear near the top if their parent is older. Is that desirable or undesirable? (Trick question: we still have no idea who or what the stream is for.)

Also [you said](https://github.com/hypothesis/h/issues/1916#issuecomment-73865477) on #1916:

    We have agreed at retrospective that we want to solve this server-side for now.

Did that change?

**Comment by gergely-ujvari** [comment]
IMO let's not talk about the purposes of the stream here, because this is out of the scope of this bug.
I agree that now the stream will show annotations those have fresh replies but it is still better than the empty 'Message not available boxes'.

If we are not content we can alter this fix to load the most recent 'root' annotations and their whole conversation. Would that be better?

Also, about server-side, I started looking at there, but since that comment with the store service it is convenient to make the requests client side without further complacating the backend search endpoint.

If we desire, I can move the functionality server-side.

**Comment by tilgovi** [comment]
I don't mean to have a conversation about what the stream is for, only to point out that this, intentionally or not, does change the stream. It is no longer strictly chronological. New replies may be far down the stream because their root is old. I wanted to be sure that was being recognized here, independent of any judgment about whether that is a good or bad change.

As for the server vs client issue, you may remember that I favored client-side solutions to begin with, so I have no problem with that. I was just surprised to see the PR contradict the consensus on the issue without any explanation of the direction change.

I think we have to ask ourselves, then, do we want to change the behavior of the stream this way?

**Comment by gergely-ujvari** [comment]
I think we're in agreement here.
I agree: it was very good to point out that the stream's behavior will change with this. (To be more precise actually it already changed in the past when we decided not to have separate cards for replies)
It is an open question whether this is good or bad this way.

Secondly: About client vs server. Yes, there wasn't any explanation. A general symptom is that our codebase changes so fast that our previous statements lose their meaning, and maybe it was not the best not to leave the original question open (client vs backend) as an implementation detail.

**Comment by dwhly** [comment]
> This changes the behavior of the stream so that replies do not appear near the top if their parent is older. Is that desirable or undesirable?

Not to wade into the middle of things, but ok.  :)

With the nod that user stories around the stream will begin to help clarify some of these questions, I'm envisioning the following:

A user is watching the stream for activity (perhaps according to some filter).  In a future scenario, with groups, we could imagine that an educator is watching discussion across all the material for one of her courses.  A reply is made that matches the filter, and that reply is then shown in the stream.  It should probably be shown at the top. (Otherwise it is likely to never be discovered.)  I also feel like the card should probably be collapsed to feature just the reply and perhaps it's immediate parent-- but that's likely out of scope here.

**Comment by tilgovi** [comment]
Jump in. The water is great.

I also agree that if our primary story here, as "stream" would seem to imply, is a chronological view, the we need to modify this.

It may be confusing, however, if the view is chronological by most recent reply, because the cards at the top level, the roots, will not necessarily be chronological then.

Twitter manages this extremely well. I would be sad to see us do something not so great here.

I suggest we think this through a bit more, design the requirements for interface and for code, and write something solid.

One possible direction is to change the stream view not not use the thread roots as its source of cards, and instead show all annotations in a list. Some annotations might appear in multiple places, if we also showed replies under their parents, but that's maybe just fine.

**Comment by dwhly** [comment]
> It may be confusing, however, if the view is chronological by most recent reply, because the cards at the top level, the roots, will not necessarily be chronological then.

Yeah, exactly.  (That would be the rationale for collapsing ancestors.)

> Some annotations might appear in multiple places, if we also showed replies under their parents, but that's maybe just fine.

My email client (Airmail on the Mac) does *exactly* this.  

Each cards features only the new thing.  I can expand the card and explore the whole email history from any card. 

Scroll a bit further down and there will be another card for an earlier part of the thread.  Ancestors and children are discoverable there too if I click to expand.

We clearly have the same considerations.  It might be one practical solution.

I think they have some heuristics to hide duplicates if they're both potentially visible in the same viewport, just showing the most recent-- though it's hard to tell sometimes since i get so much email.

I

**Comment by tilgovi** [comment]
Agree with everything you said, @dwhly. Twitter also shows the duplicates, and I think they may have some criteria for hiding them as well.

I suggest an incremental approach with the following steps:

- Source the cards from all the annotations. (We should stop using the thread service as the canonical storage, but for the moment `threading.root.flattenChildren` is probably the easiest way to do this.
- We should probably rework the updater so that we're not _watching_ this expression, since flattening the whole thread hierarchy on every scope digest is undoubtedly bad.
- The former has the nice side effect of making it possible to mutate the card contents after the initial render.
- We can insert some prompt or indicator that allows one to load the parent into the card, making it possible to expand the conversation when looking a stream that only shows the reply.

The benefits are:

- Probably a better UI
- No need to make many requests on initial load
- We start to think about where the canonical store for annotations client-side should be.
- Probably a reduction in the digest overhead

With all this in mind I'd conclude that the current PR is probably not the right approach, but I'll leave it to @gergely-ujvari to decide whether to close it and start a new one or force push some work at a new direction.

**Comment by gergely-ujvari** [comment]
Closing in favor of #2069

**Pull request closed without merging**
