### PR TITLE
Always deploy the correct Docker image version

### PR DESCRIPTION
**Pull request by seanh**
Fixes https://github.com/hypothesis/h/issues/7658. For details see: https://github.com/hypothesis/via/pull/814

### CODE REVIEW

**Comment by seanh** [comment]
I believe this will break the deployment workflow. New versions of the WebSocket app are not being built and published to Docker Hub (https://github.com/hypothesis/h/issues/7669) and the hard-coded `latest` in `deploy.yml` is the only thing that's preventing the deployment workflow from crashing: it just keeps deploying the `latest` version of the WebSocket (which is two months old). We need to fix https://github.com/hypothesis/h/issues/7669 before we can merge this PR and fix https://github.com/hypothesis/h/issues/7658

**Review by indigobravo — CHANGES_REQUESTED** [review]
> I believe this will break the deployment workflow

You are right. We need to work a solution to build a separate Docker image for the websocket...

**Comment by seanh** [comment]
> > I believe this will break the deployment workflow
> 
> You are right. We need to work a solution to build a separate Docker image for the websocket...

Or we need to change h to have only one Docker image. I'd like to investigate that first as I think it might be a simpler and more consistent solution. I'd rather not have one project that's differs from all the others by having two `Dockerfile`'s, and would rather not complicate our deployment workflows with that unless really necessary. I suspect that h and WebSocket can work with a single `Dockerfile` that gets deployed to different Elastic Beanstalk environments with different environment variables. We'll see

**Comment by seanh** [comment]
I think this PR is now safe to merge after https://github.com/hypothesis/h/pull/7674 was merged: the separate WebSocket Docker image is no longer used, we just build and publish a single Docker image and deploy the same image to all environments

**Review by indigobravo — APPROVED** [review]
👍

**Pull request merged**
