### PR TITLE
Require PyJWT>=1.0.0,<2.0.0

### PR DESCRIPTION
**Pull request by jpadilla**
Yesterday we released PyJWT [v1.0.0](https://github.com/jpadilla/pyjwt/releases/tag/1.0.0) which fixes some reported security vulnerabilities. Although this project doesn't seem to be affected, it would still be good idea to require PyJWT>=1.0.0,<2.0.0 instead.

### CODE REVIEW

**Comment by tilgovi** [comment]
Thanks for the outreach, @jpadilla, that's really awesome!

**Comment by jpadilla** [comment]
@tilgovi glad to help.

Are you only using `HS256` here? If so I'll go ahead and specify that explicitly for encoding/decoding.

**Comment by tilgovi** [comment]
Yep.

**Comment by tilgovi** [comment]
Ah, and as I raised in the PyJWT tracker, I'm using jwt.api.load and jwt.api.verify_signature directly. Those seem to have moved again, which is why the tests are failing.

**Comment by tilgovi** [comment]
If you want to change things to just use decode(verify=False) that's fine. I can temper my urge to over-optimize.

**Comment by tilgovi** [comment]
Thanks _so_ much!! Only thing missing is to remove the import at the top of the file so we stop trying to get the private API.

**Comment by jpadilla** [comment]
@tilgovi yeah, sorry about that. Also fixing auth_test.py which patches those two non existing methods.

**Comment by jpadilla** [comment]
@tilgovi sorry about the back and forth, relying on Travis to run tests, since I couldn't get a local setup working.

**Comment by tilgovi** [comment]
No worries at all! Thanks, again. :cake:

**Comment by jpadilla** [comment]
@tilgovi definitely need some help to fix that test.

**Comment by jpadilla** [comment]
I can't probably check for `self.decode.assert_*` multiple times in that test like that.

**Comment by tilgovi** [comment]
I'll take a look later this evening. You can access assertions about each
call. I just don't remember the API from memory.

Thanks so much for getting involved with this.

**Comment by jpadilla** [comment]
@tilgovi :fireworks: think i've got it now!

**Comment by tilgovi** [comment]
@jpadilla thanks so much. I'm still a little floored that you took the time to do such great outreach and proactive patching around this. Not to be tossing around gold stars or anything, but can we send you some stickers or something? Email me if you like.

**Pull request merged**
