### PR TITLE
Changes space between group members

### PR DESCRIPTION
**Pull request by lenazun**
Changes the space between items in the group members list. Reduces the space between documents a little, to make them a bit more balanced.

### CODE REVIEW

**Comment by lenazun** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SVWLXWMH&#x2F;321-bug-group-member-names-have-too-much-space-between-them"> [BUG] Group member names have too much space between them</a>

**Comment by lenazun** [comment]
group_spacing
@conordelahunty for your review

**Comment by palesun** [comment]
Thank you Lena

**Comment by nickstenning** [comment]
LGTM.

**Pull request merged**
