### PR TITLE
Reorganize the HACKING docs

### PR DESCRIPTION
**Pull request by seanh**
Sphinx's navigation doesn't support "sub pages" like when HACKING.rst says "go
to either HACKING.Debian.rst or HACKING.OSX.rst and then come back to this page
and continue with the next section". Sphinx's navigation links will send the
user round in circles. It has to be linear like a book.

- Move HACKING*.rst into new docs/hacking/ folder
- Add docs/hacking/index.rst, front/index page for the new hacking chapter
- New docs/hacking/install.rst contains all the installing and running
  instructions in one nice, linear, long page. Users can just follow this from
  top to bottom to install and run h in a dev environment.
- In particular HACKING.Debian.rst, HACKING.OSX.rst and elasticsearch.rst
  which were their own pages are now sections inlined in this long page.
- Only one "Installing" entry in the main table of contents (not all the
  sections/steps listed)
- Other pages like building the browser extensions, code quality, etc have
  just been moved into the hacking/ folder.

### CODE REVIEW

**Comment by seanh** [comment]
If this gets merged then next steps will be:

* _Code quality_ page will becomes a general _How to submit a pull request_ page including feature branching, commit messages, coding standards .... and that you should add a line to the changelog! Should be useful both

**Comment by seanh** [comment]
If this gets merged then next steps will be:

* _Code quality_ page will becomes a general _How to submit a pull request_ page including feature branching, commit messages, coding standards .... and that you should add a line to the changelog! Should be useful both for pull request submitters and reviewers

* _Writing documentation_ page can grow into a guide for how to write docs / documentation standards

* As we need to we can add new pages to the hacking guide for specific topics (like we already have for customized embedding, serving over ssl, etc). It's scalable.

**Comment by seanh** [comment]
Oh, and _Hacking guide_ should probably be renamed to _Contributing guide_ at some point since it'll grow to include things like how to contribute docs, bug reports, translations..

**Comment by nickstenning** [comment]
LGTM.

**Comment by seanh** [comment]
Well, that got merged faster than I expected :) I probably broke some links in the README, I'll fix that..

**Pull request merged**
