### PR TITLE
Make userid mandatory

### PR DESCRIPTION
**Pull request by seanh**
Depends on https://github.com/hypothesis/h/pull/4321

You can't create a Token without a userid (you can create the Python
object fine, but if you add it to a db session and then try to flush or
commit that session you will get an IntegrityError - userid is not
nullable in the database).

Make the userid arg a positional arg on the Token class so that its
mandatoriness is explicit and so that you can't create an invalid ORM
object.

### CODE REVIEW

**Comment by nickstenning** [comment]
Can you expand on the problem that this is trying to solve? A token without a userid isn't valid *for persistence*, sure, but aren't you going to discover that the first time you try and save one?

**Comment by seanh** [comment]
On master, the `IntegrityError` from psycopg2 won't come until you flush or commit the db session, which could be far away from the bug (where a `Token` without a `userid` was created and added to the session). So the problem that I'm trying to fix here is the potential for difficult to find bugs to creep in.

On this branch you'll get a `TypeError` as soon as you try to init a `Token` without a `userid`, and the traceback will show you the line of code where the bug is.

**Comment by nickstenning** [comment]
My concern is that in general overriding SQLAlchemy constructors causes more pain than it's worth. I'm not really convinced that whatever gains are to be had by making this mandatory at construction time are greater than the loss of consistency between sqla models.

**Comment by seanh** [comment]
Do you mean consistency in that arguments usually have to be passed as named rather than positional args to sqla constructors? `Token(userid='foo')` rather than `Token('foo')`?

**Comment by nickstenning** [comment]
Do we still want/need this change?

**Comment by seanh** [comment]
I guess not

**Pull request closed without merging**
