### PR TITLE
Update annotation.coffee

### PR DESCRIPTION
**Pull request by judell**

### CODE REVIEW

**Comment by judell** [comment]
Until drafts persist, let's help people avoid losing their work.

**Comment by nickstenning** [comment]
If we want to fix the problem, let's fix the problem. Until then, I think giving people workarounds just makes it look like we don't care.

**Comment by tilgovi** [comment]
Agreed, @nickstenning

**Comment by BigBlueHat** [comment]
Proposing #2361 over this one--given feedback that said updating text wasn't enough.

**Pull request closed without merging**
