### PR TITLE
Remove urls in reply notification emails for third party users

### PR DESCRIPTION
**Pull request by sheetaluk**
Fixes https://github.com/hypothesis/h/issues/4720

### CODE REVIEW

**Comment by hmstepanek** [comment]
I had another thought on this. Is the parent authority ever different than the user authority? The reason I ask is because the test case is the same for both the parent and the user. If they aren’t ever going to be different then we probably don’t need to pass 2 args into the context-1 would suffice.

**Comment by fatbusinessman** [comment]
I have a suggestion for an alternative approach, for what it’s worth. Feel free to go with it or not, as you both see fit.

As the PR currently stands, it’s passing in Booleans for `is_third_party_parent_user` and `is_third_party_reply_user`, and the template is using those to determine whether to render the `parent_user_url` and `reply_user_url` respectively. Might it simplify matters if you eliminated the Booleans, and instead passed in `None` (or some other appropriate value that Python considers false-y) for the URLs themselves? After all, the template doesn’t necessarily need to care *why* a user does or doesn’t have a URL associated with them.

This would change the template pattern from:

```
  {% if is_third_party_reply_user %}
    {{ reply_user_display_name }}
  {% else %}
    <a href="{{ reply_user_url }}">{{ reply_user_display_name }}</a>
  {% endif %}
```

to:

```
  {% if reply_user_url %}
    <a href="{{ reply_user_url }}">{{ reply_user_display_name }}</a>
  {% else %}
    {{ reply_user_display_name }}
  {% endif %}
```

It looks like this would reduce the amount of stuff you would need to pass into the template, and eliminate the risk @hmstepanek brought up of a template accidentally rendering a URL it shouldn’t (because it’s not there in the first place).

How does that sound?

**Comment by robertknight** [comment]
> I had another thought on this. Is the parent authority ever different than the user authority?

Good question. In user-facing terms, this is asking whether a third-party user (managed by a publisher) can reply to an annotation created by a first party user (managed by us) or vice-versa. The answer is currently "no". Annotations and replies live in groups and only users from one specific authority can create annotations or replies in a given group.

The approach here works fine, although I do like @fatbusinessman's suggestion to model `reply_user_url`/`parent_user_url`'s as a `unicode or None`-type and then switch on that in the template.

In tests, consider using [pytest.mark.parametrize](https://docs.pytest.org/en/latest/parametrize.html) to avoid writing a lot of code for very similar tests.

**Comment by hmstepanek** [comment]
I like the alternative that @fatbusinessman proposed as well! I’m a fan. 😂

**Pull request merged**
