### PR TITLE
Rework sidebar drag resize

### LINKED ISSUE #305: Drag / resize only expanding sidebar, not shrinking.
Drag resize has been flaky for a while.  Mac OSX / Chrome on dev.h.  Can't seem to shrink sidebar only expand, and hard to expand at that... need to drag very slowly.

### PR DESCRIPTION
**Pull request by tilgovi**
Now using Hammerjs.

- Swipe or drag the toggle to open/close.

- The sidebar is clamped to not ever be pushed beyond the right
  edge of the screen.

Fix #305

### CODE REVIEW

**Comment by tilgovi** [comment]
I'll break the handlers out into methods that can be unit tested tomorrow.

**Comment by dwhly** [comment]
Nice!  Possible to see in a dokku?

**Comment by judell** [comment]
Sounds like a sweet solution, thanks!

**Comment by tilgovi** [comment]
The real trick was setting pointer events for the iframe off during drag. That avoids any need to echo mouse events over postMessage.

**Comment by tilgovi** [comment]
The rest is sugar and it feels great.

**Comment by RawKStar77** [comment]
Yeah, this is beautiful. I also noticed that you've managed to resolve the problem where if you accidentally resized the sidebar *a tiny bit*, it would appear that the sidebar wouldn't open. 

I would be happy to merge this. 

I also like the choice of including Hammer.js. It's small and has many useful things in it which I look forward to experimenting with!

**Comment by tilgovi** [comment]
I'm just beautifying the code and making an attempt to test some part of it.

**Comment by tilgovi** [comment]
Now with more code clarity and some amount of tests.

**Comment by tilgovi** [comment]
Dokku at https://hammer.dokku.hypothes.is/

**Comment by RawKStar77** [comment]
This looks and works great. Very nicely done @tilgovi.

**Comment by tilgovi** [comment]
Thanks. Opened #2162 to address one remaining problem that @judell identified.

**Pull request merged**
