### PR TITLE
Fix icon spacing

### LINKED ISSUE #3386: Larger gap between share and reply buttons
### Steps to reproduce
1. Open an annotation card

### Expected behaviour
spacing should be identical between all buttons

### Actual behaviour
it's not

screenshot 2016-05-30 09 55 47

### PR DESCRIPTION
**Pull request by nickstenning**
Remove excess whitespace on either side of icon glyphs

The annotation action icons didn't seem to be equally spaced due to excess whitespace on either side of the icons within the font glyphs. This commit updates the edit, reply and share icons to remove excess whitespace.

Where previously these three icons were 16px wide (and the trash icon was 9.5px wide) they are now 14px, 13.5px, and 12px wide respectively.

This PR also includes a commit which switches layout of the action buttons component to flexbox, so that the inter-button spacing is specified entirely using margin on the buttons, and doesn't depend on DOM whitespace insertion.

Fixes #3386.

### CODE REVIEW

**Comment by nickstenning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;QPzkIJLB&#x2F;365-bug-icon-spacing"> [BUG] Icon spacing</a>

**Comment by nickstenning** [comment]
Before:

image

This branch:

image

**Comment by nickstenning** [comment]
And if it's not clear what 02c7ec5 is all about, I knocked up [a demonstration of the problem `display: flex;` solves](http://codepen.io/nickstenning/pen/KMwEbr).

**Comment by nickstenning** [comment]
Have checked that @conordelahunty is happy with this. While Robert is away does any of @sheetaluk, @chdorner, or @seanh fancy looking at this one?

**Comment by chdorner** [comment]
LGTM.

**Pull request merged**
