### PR TITLE
Rename account settings URLs

### PR DESCRIPTION
**Pull request by finitud**
As per step#1 in https://trello.com/c/G3kr1awd/392-account-settings-profile-etc-forms-updates

### CODE REVIEW

**Comment by nickstenning** [comment]
A quick grep tells me that there's some API documentation which needs updating.

Also, we should update the route names to `account_*` rather than `profile_*`, and rename the relevant templates and layouts.

If you update the API docs I'll merge this, and then perhaps let's do the other changes in another PR.

**Comment by nickstenning** [comment]
@finitud Did you see my comment?

**Comment by finitud** [comment]
@nickstenning yep, taking care of this one now.

**Comment by nickstenning** [comment]
LGTM.

**Pull request merged**
