### PR TITLE
Add API Blueprint Markdown-based docs

### PR DESCRIPTION
**Pull request by BigBlueHat**
http://apiblueprint.org/ has more on the format.

Just the beginning. :smile:

### CODE REVIEW

**Comment by tilgovi** [comment]
Were these generated from real requests? I see example responses. Should we make these into simplified examples or did some dashboard make these?

**Comment by BigBlueHat** [comment]
These are direct cribs from the Stream at whatever point I wrote the docs. :smile: I figured they were as close to exemplar as anything I could concoct, so they'd serve the purpose just as well (or better) than handcrafted examples.

You OK with that? or do you want something different?

**Comment by tilgovi** [comment]
For the purpose of docs we should maybe trim these down a little.

**Comment by BigBlueHat** [comment]
Yeah. Agreed.

**Comment by BigBlueHat** [comment]
@tilgovi I've gone in a few times to trim these down, but I keep feeling like I'm doing a disservice to the experience by remove the "reality" from them. Is it just that it's super long?

Would you be OK if I set a return value to just 2 annotations (when "mocked") vs. the full 20 (our default)?

The first two in the list are actually pretty representative: a reply and it's parent.

**Comment by nickstenning** [comment]
The purpose of the docs is to show the structure of the API responses. We can do that without returning full JSON serializations of 20 annotations. Including just one and an ellipsis would get the job done. Let's either get this updated and merged or closed.

**Comment by BigBlueHat** [comment]
So the tension here isn't about whether to show an absurdly huge dump of JSON in our docs or not...in case that was unclear. :stuck_out_tongue: 

It's that [apiary.io](http://apiary.io/) provides a console and mock server to test client code against. If we change the listing sample code to something less than some sort of full JSON listing, then we'd break the mock server--afaik.

That's, obviously, not a big deal if we don't plan on using it. :smile: 

Anyhow...that's been the hold up with me debating it internally.

I'm happy to do the cleanup, so you can continue yours. :wink:

**Comment by tilgovi** [comment]
I'd like us to consider swagger. It seems to be getting use from some significant projects. It looks to have anything we'd like in terms of tooling. I'm particularly interested in the fact that there looks to be a swagger client for angular which would replace my sneaky/hideous hacks against our current discovery endpoint.

http://swagger.io/

**Comment by BigBlueHat** [comment]
Yeah...yeah... :wink: 

Here's a good comparison of the top 3 API doc things in this space:
http://www.mikestowe.com/2014/07/raml-vs-swagger-vs-api-blueprint.php

Really...like APIs...they're all 80% the same with 20% being the color of your bike shed....or whether or not they're compatible with your brand of tools.

I guess we just pick one that matches our current set of kit and hope for the best. :smile:

**Comment by tilgovi** [comment]
Replaced by #2099 for now.

**Pull request closed without merging**
