### PR TITLE
Add annotation dict factory for unit tests

### PR DESCRIPTION
**Pull request by seanh**

### CODE REVIEW

**Comment by tilgovi** [comment]
Unit tests for the fixtures??

**Comment by tilgovi** [comment]
:)

**Comment by tilgovi** [comment]
Looks fine, but I trust @nickstenning more than myself when it comes to good testing practice so I'll wait for him to look.

**Comment by nickstenning** [comment]
LGTM, although I'm with @tilgovi -- I think unit tests for the fixtures is probably over-keen!

**Pull request merged**
