### PR TITLE
Replace `pyramid_layout` with jinja extensions

### PR DESCRIPTION
**Pull request by jon-betts**
So far this PR demonstrates removing one of the two "panels" our app has which use `pyramid_layout` (https://pypi.org/project/pyramid_layout/).

This replaces the somewhat magical approach to attaching stand alone "panels" with their own associated templates with normal Jinja2 includes and some methods attached to the request object. These are called `widgets` primarily to make them easy to find in the code with grepping.
 
`pyramid_layout` doesn't appear to do anything when we use Pyramid 2.0 and it's pretty badly out of maintenance (max Python support 3.3). For example, the last two commits to that project were 3 months and 9 years ago. The one three months ago was me.

### CODE REVIEW

**Comment by robertknight** [comment]
One of the conceptually nice aspects of panels is that it provided a way to create components isolated from their surrounding context, implemented similarly to top-level views. I think the proposed alternative will work fine though. The main downside I can see is that a widget template could accidentally rely on context implicitly provided by the views in which it is currently used.

**Comment by jon-betts** [comment]
It would be nice if we could keep some of those characteristics, but I'm not sure how you'd go about it and how much it's worth investing the time to do seeing as we make such light use of it. I think I'd be strongly in favour of none of this UI being in `h` in the first place, but that of course is a bigger topic.

In the mean time, keeping `pyramid_layout` doesn't really seem like a realistic option, but if anyone has any ideas for other simple ways to do this which keep features we like that would be good.

**Comment by seanh** [comment]
Is widgets really the right name for this? It looks to me like you have:

1. "Includes" (already existed): the `templates/includes/` directory and `{% include "h:templates/..." %}`
2. "Template helper functions": `request.widgets.back_link_label()` looks like it's just a helper function that's made globally available for any template (include or otherwise) to call

It looks to me like `back_link_label()` is only intended to be called by templates not other parts of the code. In that case I wonder whether it could be made part of the template environment, rather than part of the request? You could use [`config.add_jinja2_extension()`](https://docs.pylonsproject.org/projects/pyramid_jinja2/en/latest/api.html#pyramid_jinja2.add_jinja2_extension) or you can call [`config.get_jinja2_environment()`](https://docs.pylonsproject.org/projects/pyramid_jinja2/en/latest/api.html#pyramid_jinja2.get_jinja2_environment) and then add things to the [`jinja2.Environment`](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.Environment).

This is already used in h. For example templates can call `svg_icon(...)` which is [implemented in `jinja_extensions.py`](https://github.com/hypothesis/h/blob/master/h/jinja_extensions.py#L61-L116) and [registered in `app.py`](https://github.com/hypothesis/h/blob/9b5cd40f052e0b9e00cc09cc6f29e161a31c93bc/h/app.py#L54).

The other thing I'm wondering about is the global-ness. `back_link()` seems specific to certain activity pages views rather than something you'd make globally available to all views. Is there a way to make these more context-specific?

**Comment by jon-betts** [comment]
I could do it as the Jinja extension you suggest. It would need to get the `request` passed in, but that's no biggie.

I don't really see the global-ness of this as a downside (within the Jinja2 world), as the previous solution was globally available through `panels()`. It's a think we could solve, but I don't think we have to unless there's a mega obvious way of doing it?

**Comment by jon-betts** [comment]
I've redone these as Jinja extensions which means they are only available in the templates. They aren't purely available in specific templates of course as this isn't how this works.

**Review by seanh — APPROVED** [review]

**Pull request merged**
