### PR TITLE
Add enter/exit animation when adder is shown

### PR DESCRIPTION
**Pull request by robertknight**
Add an entry animation for the adder which makes it 'pop up' or 'pop
down', depending on which direction the arrow is pointing.

Additionally, animate the color transitions when hovering over the
toolbar buttons to soften the changes.

### CODE REVIEW

**Comment by nickstenning** [comment]
I'd like @conordelahunty to sign off on this one before merging.

**Comment by conordelahunty** [comment]
@robertknight Can you send me a build

**Comment by conordelahunty** [comment]
Have tweeked the speed a little with Robert and am happy to ship that change.

**Comment by nickstenning** [comment]
:+1:

**Pull request merged**
