### PR TITLE
Save permissions to drafts service

### LINKED ISSUE #2716: Permissions are lost when changing between groups while editing an annotation
1. Edit an already saved annotation, change its permission from private to shared or vice-versa, don't save it
2. Change to a different group
3. Change back
-> The change to the permissions is lost

untitled screencast - cropped 7

Surprisingly this is _not_ the same issue as <https://github.com/hypothesis/h/issues/2713>.

### PR DESCRIPTION
**Pull request by seanh**
Fixes #2716.

### CODE REVIEW

**Comment by seanh** [comment]
Just needs a test

**Comment by seanh** [comment]
untitled screencast - cropped 8

**Comment by nickstenning** [comment]
LGTM. Add a test and we're good.

**Comment by seanh** [comment]
Done

**Comment by nickstenning** [comment]
LGTM.

**Pull request merged**
