### PR TITLE
Bump gevent version

### PR DESCRIPTION
**Pull request by tilgovi**
This should stop the logging that occurs when clients disconnect.
https://github.com/gevent/gevent/pull/377

### CODE REVIEW

**Comment by tilgovi** [comment]
Also should fix the SSL problems @robertknight found.
Want to try it?

**Comment by nickstenning** [comment]
I'm a bit reluctant to depend on a beta release when this isn't causing us issues in production, but I'll try it out.

**Comment by tilgovi** [comment]
It's not actually important. I just wanted to share it since I did the work.

**Comment by nickstenning** [comment]
Closing -- thanks for the work, and we'll revisit this when gevent 1.1 is released.

**Pull request closed without merging**
