### PR TITLE
Restore counting of private and group annotations in badge

### PR DESCRIPTION
**Pull request by seanh**

### CODE REVIEW

**Comment by nickstenning** [comment]
LGTM. Good spot.

**Comment by dwhly** [comment]
For some reason I thought this was something we never did and decided not to b/c of add'l burden on auth/db queries or whatever.  But amazing that it's "fixed" now.

**Comment by seanh** [comment]
It was actually working before. I think.

**Comment by judell** [comment]
Pretty sure it wasn't but who cares? Will now! Thanks!

**Comment by judell** [comment]
Close this now?

**Pull request merged**
