### PR TITLE
Correct X-Annotator-Auth-Token -> Authorization

### PR DESCRIPTION
**Pull request by seanh**

### CODE REVIEW

**Comment by nickstenning** [comment]
`Authorization: Bearer <token>`, not `Authorization: <token>`.

**Comment by seanh** [comment]
Corrected

**Comment by nickstenning** [comment]
You got two, you missed three. More haste, less speed :)

**Comment by seanh** [comment]
Have I had too much coffee? I don't see what I missed

```
$  ack 'Authorization|X-Annotator' docs/
docs/api.rst
239:      Authorization: Bearer eyJhbGc[...]mbl_YBM
273:   :reqheader Authorization: JWT authentication token
300:      Authorization: Bearer eyJhbGc[...]mbl_YBM
324:   :reqheader Authorization: JWT authentication token
351:      Authorization: Bearer eyJhbGc[...]mbl_YBM
367:   :reqheader Authorization: JWT authentication token
```

I'm deliberately leaving the `:reqheader Authorization:`'s as they are, `Authorization` is the name of the header, `Bearer ` is part of the value

**Comment by nickstenning** [comment]
Ahhhhh, sorry, my bad. I was reading the `:reqheader:` bits as if they were example usage, not inline docs. Sorry about that.

**Pull request merged**
