### PR TITLE
Update outdated logo image

### PR DESCRIPTION
**Pull request by lyzadanger**
There is a report of iMessage "unfurling" and showing an old H logo. It would seem that iMessage references https://hypothes.is/assets/images/logo.png, which has an outdated variant.

There is also a `logo_new.png` in the same directory (`h/static/images/`) but the simplest thing for the moment may be to update `logo.png` to the new logo (i.e. make its contents identical to `h/static/images/logo_new.png`), which is what this little PR does.

Fixes https://github.com/hypothesis/product-backlog/issues/1115

### CODE REVIEW

**Comment by robertknight** [comment]
The old logo was 568px wide. The new logo has a width of 200px which ends up looking a little blurry in both iMessage and Facebook's [Sharing Debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fhypothes.is%2Fassets%2Fimages%2Flogo_new.png).

New logo small

New logo FB sharing debugger

**Comment by robertknight** [comment]
The only place in h that references `logo.png` is in the `og:image` meta tag. Looking at the way that iMessage and Facebook use this image, they really expect it to have a landscape aspect ratio (eg 16:9 or wider). I uploaded a higher resolution version of the new logo to Imgur and pasted the link into iMessage. It looks like this:

New logo high res

The marketing website actually already has an `og:image` [image](https://d242fdlp0qlcia.cloudfront.net/uploads/2020/05/25133654/HypothesisFeaturedDefault.png) that works better:

Marketing website logo

Since this was the only use of logo.png, perhaps we should rename it to share-image.png and replace it with the above landscape wordmark from the marketing website?

**Comment by robertknight** [comment]
Some technical resources related to choosing an image for use with `og:image`:

- Facebook: https://developers.facebook.com/docs/sharing/best-practices#images
- Apple Messages: https://developer.apple.com/library/archive/technotes/tn2444/_index.html
- Twitter: https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image

Note that neither FB nor Twitter support SVG, so we do need to keep using a PNG.

**Comment by lyzadanger** [comment]
@robertknight Thanks for doing the legwork I really shoulda done myself (was moving quickly, and thought I'd try to quick-and-dirty fix this). I think you're right: this bears a slightly higher-level think. It doesn't need to snowball into something huge, but let's do this right and get these static logo-related assets in decent shape—some haven't been touched since 2014. I'll go ahead and track this in a new issue, linking to this thread and related issues. Once I've done that—opened a tracking issue—I'll likely close this PR.

**Comment by lyzadanger** [comment]
Closing this PR as the scope is a little broader than this alone. See https://github.com/hypothesis/h/issues/6803

**Pull request closed without merging**
