### PR TITLE
Disable extremely slow auto-update of ancient timestamps

### LINKED ISSUE #1952: Timestamp updater breaks on old annotations
1. Go to this page: https://en.wikipedia.org/wiki/Main_Page
2. Activate extension

Expected result: normal browser function remains

Actual result: CPU remains locked at 100%. Browser is responsive (after the first few seconds), but the load remains high.

   * * *

Note that this is not the same issue as the d-t-m issue https://github.com/hypothesis/dom-text-mapper/issues/45, where the initial scanning phase is blocking the browser for far too long; here, the scanning completes, but the load still remains high.

Some initial profiling reveals that it's actually the [Moments library](https://github.com/hypothesis/h/blob/2fa9382fea059ac8fa8dbccce103959cd74c519f/h/static/scripts/vendor/moment-with-langs.js#L297) that's spinning the CPU.

Normally, we should only call it now and then; constantly calling it is obviously the result of a bug.

### PR DESCRIPTION
**Pull request by csillag**
In theory, this removes our ability to update
timestamps that are several months old, and we leave
them around in a browser tab for weeks.

In practice, this fixes #1952.

   * * *

As suggested by @tilgovi [here](https://github.com/hypothesis/h/issues/1952#issuecomment-74747913).

### CODE REVIEW

**Comment by tilgovi** [comment]
Maybe just change the breakpoints calculation in the helpers to return the maximum timeout. Then we have the best of everything.

**Comment by nickstenning** [comment]
Needs a test.

**Comment by csillag** [comment]
> Maybe just change the breakpoints calculation in the helpers to return the maximum timeout. Then we have the best of everything.

Done.

**Comment by tilgovi** [comment]
_in the helpers_

**Comment by csillag** [comment]
> _in the helpers_

Well, we are enforcing the 5-second minimum value at the exact same function, here: https://github.com/hypothesis/h/blob/1952-stop-spinning-timestamps/h/static/scripts/directives/annotation.coffee#L240

Is there a difference between enforcing a minimum value and a maximum value?
Or should I also move the minimum value *in the helper* ?

**Comment by tilgovi** [comment]
Maybe that clamping to five isn't needed for any reason, but yes I think
the helpers should return the appropriate timeout and the caller shouldn't
have to be concerned with these things.

Please refactor as appropriate and reevaluate that five second bit and tell
us what you determine to be the right refactoring.

**Comment by csillag** [comment]
Refactored. Now everything happens in the time helper.
We have a minimum of 5 secs, and a maximum of 24 days.

Also updated the tests.

**Comment by csillag** [comment]
> Please refactor as appropriate and reevaluate that five second bit

I think the five second bit is fine; it really makes no sense to go over all annotation cards in every second.

> and tell us what you determine to be the right refactoring.

I think it's easier to test if everything happens in the time helper, so I moved it all there.

**Comment by nickstenning** [comment]
LGTM.

**Pull request merged**
