### PR TITLE
Fix reply notification worker

### PR DESCRIPTION
**Pull request by nickstenning**
If an annotation from the reply notification queue doesn't have a parent, don't call `storage.fetch_annotation` with `None`. 

The Elasticsearch `Annotation.fetch(id)` class method (which is what this maps to under the hood) doesn't take kindly to being called with `None`.

----

This PR also takes the opportunity to remove an unused function from `h.notification.reply_template`.

### CODE REVIEW

**Comment by robertknight** [comment]
Change looks fine to me. Do you know in what situations we can end up trying to send a reply notification for an annotation that doesn't have a parent? Is this when the parent has been deleted before the notification is processed or something else?

**Comment by nickstenning** [comment]
The way that reply notifications work is that *all* annotation CRUD operations are processed to work out if replies need to be sent. So this is a *very* common occurrence.

**Comment by seanh** [comment]
To reproduce this issue, just make an annotation then have another user reply to that annotation, then run the notification worker (`hypothesis-worker conf/development-app.ini notification`):

```
Traceback (most recent call last):
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/gnsq/reader.py", line 703, in handle_message
    return self._handle_message(message)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/gnsq/reader.py", line 685, in _handle_message
    self.on_message.send(self, message=message)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/seanh/Projects/hypothesis/h/h/notification/worker.py", line 24, in handle_message
    send_notifications(message)
  File "/home/seanh/Projects/hypothesis/h/h/notification/worker.py", line 32, in send_notifications
    for (subject, body, html, recipients) in notifications:
  File "/home/seanh/Projects/hypothesis/h/h/notification/reply_template.py", line 116, in generate_notifications
    parent = storage.fetch_annotation(annotation.parent_id)
  File "/home/seanh/Projects/hypothesis/h/h/api/storage.py", line 37, in fetch_annotation
    return models.Annotation.fetch(id)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/annotator/elasticsearch.py", line 135, in fetch
    id=docid)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 328, in get
    raise ValueError("Empty value passed for a required argument.")
ValueError: Empty value passed for a required argument.
```

**Comment by nickstenning** [comment]
It was even worse than that. You didn't need to

> make an annotation then have another user reply to that annotation, then run the notification worker.

You could just 

> make an annotation, then run the notification worker.

**Pull request merged**
