### PR TITLE
Use icons for left/right pagination links

### LINKED ISSUE #3787: Paginator control < > icons needed
The current implementation uses `<` and `>` characters but these don't look quite the same as what's in the mockup, icon image files are needed instead.

### PR DESCRIPTION
**Pull request by chdorner**
Fixes #3787

### CODE REVIEW

**Comment by seanh** [comment]
Nice! Looks a lot nicer now, but I think the icon needs to turn white when the button is hovered, currently it's black:

screenshot from 2016-10-17 10-50-36

But on master and in the design it turns white on hover:

screenshot from 2016-10-17 10-51-44

pagination_-_measurements_and_states

I think Rob said something somewhere about how you can control the colour of an SVG with CSS, will try to dig it out

**Comment by seanh** [comment]
> I think Rob said something somewhere about how you can control the colour of an SVG with CSS, will try to dig it out

I couldn't find Rob's original comment, but got a rough version of this working locally, I think you have to:

1. Inline the SVG into the HTML, rather than use an `` tag; and
2. Delete the `fill="none"` and `fill="#3F3F3F"` attributes from the two `<g>` elements in the SVG code; and
3. Add `fill: currentColor;` to the `.pager__item--begin` and `.pager__item--end` CSS classes.

And now I wonder is some of the other attributes in this SVG code are also unnecessary (though it's probably not a big deal).

**Comment by seanh** [comment]
For example:

```diff
diff --git a/h/static/styles/partials-v2/_pager.scss b/h/static/styles/partials-v2/_pager.scss
index 1c6894d..3ca5408 100644
--- a/h/static/styles/partials-v2/_pager.scss
+++ b/h/static/styles/partials-v2/_pager.scss
@@ -25,6 +25,7 @@
 .pager__item--end {
   padding-top: 8px;
   padding-bottom: 6px;
+  fill: currentColor;
 }
 
 
diff --git a/h/templates/includes/paginator.html.jinja2 b/h/templates/includes/paginator.html.jinja2
index 3ca9160..519a6e8 100644
--- a/h/templates/includes/paginator.html.jinja2
+++ b/h/templates/includes/paginator.html.jinja2
@@ -11,7 +11,20 @@
         <a class="pager__item pager__item--begin pager__item--link"
           href="{{ page.url_for(page.prev) }}"
           aria-label="{% trans %}Go to previous page{% endtrans %}">
-          <img src="/assets/images/icons/pagination-left.svg" aria-hidden="true">
+
+<?xml version="1.0" encoding="UTF-8" standalone="no"?>
+<svg width="8px" height="12px" viewBox="0 0 8 12" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
+    <!-- Generator: Sketch 40.1 (33804) - http://www.bohemiancoding.com/sketch -->
+    <title>left</title>
+    <desc>Created with Sketch.</desc>
+    <defs></defs>
+    <g id="Page-1" stroke="none" stroke-width="1"fill-rule="evenodd">
+        <g id="left">
+            <polygon id="Combined-Shape" points="3.41421356 6 6.70710678 9.29289322 7.41421356 10 6 11.4142136 5.29289322 10.7071068 1.29289322 6.70710678 0.585786438 6 0.939339828 5.64644661 1.29289322 5.29289322 5.29289322 1.29289322 6 0.585786438 7.41421356 2 6.70710678 2.70710678"></polygon>
+        </g>
+    </g>
+</svg>
+
         </a>
       </li>
     {% endif %}
```

peek 2016-10-17 11-57

**Comment by chdorner** [comment]
@seanh Ah, thanks for the hint! I've seen we have a `svg_icon` helper that reads an svg file and in-lines it, I've been using that one :+1:

**Comment by seanh** [comment]
Cool, works now

**Pull request merged**
