### PR TITLE
Enable annotations on H documentation

### PR DESCRIPTION
**Pull request by robertknight**
Add Hypothes.is to H's documentation pages so
users can provide feedback or ask questions
on issues when deploying or hacking H.

### CODE REVIEW

**Comment by nickstenning** [comment]
Nice.

**Comment by tilgovi** [comment]
I'm not seeing it on http://h.readthedocs.org/en/latest/INSTALL.html

**Comment by robertknight** [comment]
@tilgovi - The documentation currently on h.readthedocs.org was last updated from commit 90026ddb86917b4b534d0124eea37e6664d7f5c1 (see the READTHEDOCS_DATA var near the top of the page source). AIUI RTD generation should be triggered via a web hook on commit, but I don't know if there are any filters - eg. does it only regenerate if particular files are modified by a commit?

**Comment by nickstenning** [comment]
Fixed.

**Comment by tilgovi** [comment]
Weird. It's still not consistently on all pages.

**Comment by tilgovi** [comment]
Oh, never mind. I don't know what I'm seeing. Maybe it was just slow.

**Pull request merged**
