### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by nickstenning**
This PR doesn't make h work on Python 3 (for one thing, we'll need to wait for gevent 1.1...) but it takes the first few steps towards compatibility.

Not to be merged just yet.

### CODE REVIEW

**Comment by tilgovi** [comment]
Do you need _compat? I would just use the `six` library. It's already a transitive dependency anyway.

**Comment by seanh** [comment]
Ooh, glad to see the start of this

**Comment by seanh** [comment]
@nickstenning Rebased this and fixed a couple more things. Take a look at h/api/models.py and h/presenters.py in particular, and if you're happy then merge

**Comment by nickstenning** [comment]
Looks good.

**Pull request merged**
