### PR TITLE
[wip] Add jscs JavaScript linting to `make lint`

### PR DESCRIPTION
**Pull request by seanh**

### CODE REVIEW

**Comment by seanh** [comment]
`make lint` should be failing now with lots of jscs complaints, want to see how it looks on Travis

**Comment by nickstenning** [comment]
You probably need to install jscs! `npm install --save-dev jscs`

**Comment by nickstenning** [comment]
Oh, sorry, I was suggesting you run that locally and commit the result.

**Comment by seanh** [comment]
RIght, didn't even look to see what --save-dev did

**Comment by seanh** [comment]
Lots of jscs errors: <https://travis-ci.org/hypothesis/h/builds/58936085>

**Comment by nickstenning** [comment]
While Hound doesn't support running jscs yet, it looks like they [might in due course](https://github.com/thoughtbot/hound/issues/418). In the mean time I'm going to close this.

**Pull request closed without merging**
