### PR TITLE
Topbar toolbar harmony

### PR DESCRIPTION
**Pull request by tilgovi**
commit 4327524cea577929dd98a356fbe829f2dbc010e6
Author: Randall Leeds <tilgovi@hypothes.is>
Date:   Fri Jun 26 19:50:52 2015 -0700

    Make the search icon clickable
    
    When the search icon is clicked give focus to the search input.

commit e65af313c193ea0cf54f5012c663f115f7ab455a
Author: Randall Leeds <tilgovi@hypothes.is>
Date:   Mon Jun 22 15:56:49 2015 -0700

    Make top bar style consistent with toolbar
    
    Harmonize the styles of the buttons in the top bar and the toolbar.
    
    - Match font size at 18px
    - Buttons are .btn-clean and have minimum width so icons are square
    - Transitions for background color
    - Simplify the styles for the top bar, using the newly consistent
      clean top bar button styles instead of specific styles for the
      share button.

### CODE REVIEW

**Comment by tilgovi** [comment]
We may wish to revert 5ddf07fe132e30a469c12fb5bf0b05d8a6447a00 after this.

**Comment by dwhly** [comment]
Is a dokku possible for this?

**Comment by JakeHartnell** [comment]
https://topbar-toolbar-harmony.dokku.hypothes.is/

**Comment by tilgovi** [comment]
@JakeHartnell this is updated.

**Comment by tilgovi** [comment]
Let me know if you still have problems and what browser you're using and I'll try to fix.

**Comment by JakeHartnell** [comment]
Looking good! This is super nit-picky, but on Firefox and Chrome in ubuntu, 'Search...' has vertical allignment that is still slightly off. It needs to be nudged down a pixel or two.

Firefox:
selection_094

Chrome:
selection_095

**Pull request merged**
