### PR TITLE
Fix dangerous default values

### PR DESCRIPTION
**Pull request by seanh**

### CODE REVIEW

**Comment by robertknight** [comment]
> Looks like someone (me) needs a Python default arg lesson.

🙋‍♂️ have also been caught out by this a few times, since neither JS nor C++ work this way.

**Comment by seanh** [comment]
Totally forgot about this PR, I meant to add a description to it.

I found these by running `prospector` on an individual file like this:

```shellsession
$ prospector tests/h/views/activity_test.py
```

I do this on my own PRs and when reviewing other people's. We have too many `prospector` warnings in the h codebase for running it over the entire codebase to be useful. Until we've dealt with that problem (which I have a plan for, just need to find the time to get around to it) I recommend running it manually on the individual files you're working on, as this'll usually produce a small enough output hat you can scan it for any problems that you actually want to fix. (`prospector` finds many things that `flake8` doesn't.)

You can also run it on the whole codebase and get all instance of just one warning:

```shellsession
$ prospector -o pylint | ag dangerous-default
```

The `-o pylint` just changes the output format to a pylint-style one-line-per-warning format that's suitable for easily piping to `ag` or `grep` (it still runs all the linters, not just `pylint`).

**Comment by seanh** [comment]
This PR needs tests

**Comment by seanh** [comment]
Test coverage issues fixed.

@lyzadanger Can you take another look?

In one case I've removed the argument default value because the default was never used and so wasn't being covered by the tests (we should pay more attention to coverage in code reviews: it can tell us about unused code).

In another case I removed an argument entirely because it was only ever being used by the tests, and only to pass in the same value as was the default value.

**Comment by lyzadanger** [comment]
> (we should pay more attention to coverage in code reviews: it can tell us about unused code).

Yes! I wish codecov weren't quite so...temperamental because sometimes there are incredibly-vital gems in its report. The other day it helped me find a test that wasn't getting run at all!

**Pull request merged**
