### PR TITLE
Realtime notifications for pages with the same link

### LINKED ISSUE #1815: Realtime notifications for pages with the same link
Current situation:
If two pages which are has the same canonical/short etc. link live under different uri 
ie. http://www.forbes.com/sites/realspin/2014/03/31/the-ipccs-latest-report-deliberately-excludes-and-misrepresents-important-climate-science/print/ and 
http://www.forbes.com/sites/realspin/2014/03/31/the-ipccs-latest-report-deliberately-excludes-and-misrepresents-important-climate-science/
then if you create an annotation in one of them, only the clients with the same uri will get the realtime updates.

We have to improve our backend to use the annotator-store document plugin to also send the notifications to all discovered "equivalent" pages.

### PR DESCRIPTION
**Pull request by gergely-ujvari**
For any filter-type websocket message the clauses are scanned.
For all uri clauses the equivalent uris are fetched (with the
document plugin) and placed into the filter payload.

This way an annotation created in one of the linked pages is
sent via websocket to every linked pages

Fix #1815

### CODE REVIEW

**Comment by tilgovi** [comment]
I like it! I think other language might be clearer, that's all. Maybe "expand_uris" as the task makes more sense than "patch".

**Comment by csillag** [comment]
Will this change enable automatically sending over existing annotations when new equivalences are discovered / recorded, or only the annotations created henceforward?

**Comment by gergely-ujvari** [comment]
A separate PR will handle things to be done new equivalences are discovered.
This PR only handles using already discovered equivalences.

**Comment by csillag** [comment]
> A separate PR will handle things to be done when new equivalences are discovered.
> This PR only handles the case of using already discovered equivalences.

That's still an improvement.

**Comment by gergely-ujvari** [comment]
Okay, renamed the function names.

**Comment by gergely-ujvari** [comment]
Any more comments?

**Comment by tilgovi** [comment]
Clean.

**Pull request merged**
