### PR TITLE
(1/3) Open sidebar and set selection when '#annotations' URL fragment is present

### PR DESCRIPTION
**Pull request by robertknight**
This is the first part of adding support for '#annotations' URL fragments in the client.
This PR covers:

1. Detecting when a tab URL contains '#annotations' and automatically injecting H in the Chrome extension
2. Detecting when Annotator is loaded into a document (by the extension, bookmarklet or embedder) containing '#annotations' in the URL fragment, automatically opening the sidebar and passing the annotation ID through to the client
3. Initializing the annotation selection from the value passed through in step (2)

Subsequent PRs will cover:
 1. Switching the focused group to the one containing the annotation, if necessary
 2. Preserving the intent to select an annotation after signing in
 3. Displaying a suitable message if the user does not have permission to access the annotation

### CODE REVIEW

**Comment by robertknight** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dlSUhwO&#x2F;256-allow-a-url-fragment-to-trigger-the-client-to-focus-a-specific-annotation-on-load"> Allow a URL fragment to trigger the client to focus a specific annotation on load.</a>

**Comment by nickstenning** [comment]
As discussed in Slack, this is all looking good except that we need to ensure that multiple extensions don't all try to inject at the same time.

**Comment by robertknight** [comment]
Previous comment addressed in a separate PR in #3097

**Comment by nickstenning** [comment]
LGTM. One question to consider -- I assume we want to scroll to the annotated content as well?

**Comment by robertknight** [comment]
> I assume we want to scroll to the annotated content as well?

Yes. That's an important addition that's needed. I'll make a note on the card.

**Pull request merged**
