### PR TITLE
Update CHANGES for v0.4.0

### PR DESCRIPTION
**Pull request by BigBlueHat**
We haven't done these in awhile, so I thought it might be prudent to get a review of the CHANGES update.

Anything else need to be "bumped" other than this and the git tag (which I'll make once this is merged)?

Answer that, give it a +1, and imma :ship: it.

### CODE REVIEW

**Comment by nickstenning** [comment]
It should be a matter of 30 minutes to skim the commit log and pull out a few major changes, that plus an additional line denoting many new fixes and improvements would read somewhat less like

> "Did you just tell me to go f*&! myself...?"
> "... I believe I did, Bob. I believe I did."

:)

**Comment by BigBlueHat** [comment]
So much for change log bankruptcy...

Let me see if I can pay down some of our back taxes. More in a bit.

**Comment by nickstenning** [comment]
Don't go nuts. Just having three or four major changes would make it look like we cared :)

**Comment by tilgovi** [comment]
`git log --merges` should help

**Comment by BigBlueHat** [comment]
A much nicer `CHANGES` update which (now) actually lists changes!!1! :smile: 

If you like it, :shipit: and release it:
https://github.com/hypothesis/h/releases/new

I'd use the "pre-release" checkbox, but otherwise just name it `v0.4.0`

Also, a copy/paste of the changes into that form would be slick!

Lastly, if you don't want to do any of that, I can tomorrow morning.

Cheers! :dancer:

**Comment by tilgovi** [comment]
I'd strip the Next Release header off the top of the changelog so we can commit and tag this. Then, we add that header back with follow-up changes, I would think. The change log should be clean on the tag.

**Comment by tilgovi** [comment]
I'll do this now. Thanks so much, @BigBlueHat. This rocks.

**Comment by BigBlueHat** [comment]
:sunglasses:

**Comment by gergely-ujvari** [comment]
Nicely done @BigBlueHat :+1:

**Comment by judell** [comment]
And there was much rejoicing. Thanks!

**Pull request merged**
