### PR TITLE
Add an "introduction to the h codebase" to the docs

### PR DESCRIPTION
**Pull request by nickstenning**
Add a relatively short orientation guide to our developer documentation. My hope is that this will help people get up to speed faster by explaining:

- what can be found where
- what is intentional, and what is accidental or "legacy"
- the distinction between h and memex

### CODE REVIEW

**Comment by nickstenning** [comment]
I've requested reviews from one old hand and one new person, to make sure that this a) isn't bullshit and b) is intelligible to someone who is new. Thank you for checking it out!

**Comment by nickstenning** [comment]
When you get a chance, @fatbusinessman, would you mind reading through this and seeing if it makes sense to you?

**Comment by fatbusinessman** [comment]
Yup, no problem, @nickstenning: that’s on my list for today.

**Comment by nickstenning** [comment]
Great. Thanks both for the reviews. Merging.

**Pull request merged**
