### PR TITLE
Upgrade node-sass to 4.4.0

### PR DESCRIPTION
**Pull request by nickstenning**
More recent versions of node-sass include binary SASS builds that link against musl so we can get rid of our own vendored version.

### CODE REVIEW

**Comment by nickstenning** [comment]
I'm just checking what actually changes between master and this branch:

```diff
--- master-manifest.json        2017-01-27 12:18:08.000000000 +0000
+++ upgrade-sass-manifest.json  2017-01-27 12:20:24.000000000 +0000
@@ -11,7 +11,7 @@
   "images/wordmark.png": "images/wordmark.png?ef70c8",
   "scripts/admin-site.bundle.js": "scripts/admin-site.bundle.js?a681d4",
   "scripts/admin-site.bundle.js.map": "scripts/admin-site.bundle.js.map?bbdc09",
-  "scripts/bootstrap.bundle.js": "scripts/bootstrap.bundle.js?f1ccdc",
+  "scripts/bootstrap.bundle.js": "scripts/bootstrap.bundle.js?c131b8",
   "scripts/bootstrap.bundle.js.map": "scripts/bootstrap.bundle.js.map?427721",
   "scripts/header.bundle.js": "scripts/header.bundle.js?becf27",
   "scripts/header.bundle.js.map": "scripts/header.bundle.js.map?5b72d7",
@@ -21,21 +21,21 @@
   "scripts/legacy-site.bundle.js.map": "scripts/legacy-site.bundle.js.map?475fa0",
   "scripts/raven.bundle.js": "scripts/raven.bundle.js?4a39ba",
   "scripts/raven.bundle.js.map": "scripts/raven.bundle.js.map?96aeda",
-  "scripts/site.bundle.js": "scripts/site.bundle.js?ada060",
+  "scripts/site.bundle.js": "scripts/site.bundle.js?33c42c",
   "scripts/site.bundle.js.map": "scripts/site.bundle.js.map?b9a310",
   "scripts/unorm.bundle.js": "scripts/unorm.bundle.js?caac90",
   "scripts/unorm.bundle.js.map": "scripts/unorm.bundle.js.map?080020",
   "styles/admin.css": "styles/admin.css?e0a323",
-  "styles/admin.css.map": "styles/admin.css.map?ab031b",
+  "styles/admin.css.map": "styles/admin.css.map?1789d7",
   "styles/bootstrap.css": "styles/bootstrap.css?06783b",
   "styles/front-page.css": "styles/front-page.css?b2e22a",
-  "styles/help-page.css": "styles/help-page.css?8a29c2",
-  "styles/help-page.css.map": "styles/help-page.css.map?8ef3a4",
+  "styles/help-page.css": "styles/help-page.css?7ea98d",
+  "styles/help-page.css.map": "styles/help-page.css.map?b13766",
   "styles/icomoon.css": "styles/icomoon.css?f3ad74",
   "styles/old-home.css": "styles/old-home.css?ca1245",
-  "styles/old-home.css.map": "styles/old-home.css.map?921325",
+  "styles/old-home.css.map": "styles/old-home.css.map?4b98f4",
   "styles/site.css": "styles/site.css?9d2d50",
-  "styles/site.css.map": "styles/site.css.map?ff88cc",
+  "styles/site.css.map": "styles/site.css.map?3c13bb",
   "images/favicons/android-chrome-192x192.png": "images/favicons/android-chrome-192x192.png?0397c6",
   "images/favicons/favicon-16x16.png": "images/favicons/favicon-16x16.png?e532f4",
```

**Comment by nickstenning** [comment]
And here's the only actual CSS change, to `help-page.css`:

```diff
bottom:7px solid [-#fff;content:"";position:absolute;left:-7px;top
:1px}.open>.dropdown-menu__top-arrow{visibility:visible}.dropdown-menu__row{display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-orient:horizontal;-webkit-box-direction:normal;-ms-flex-direction:row;flex-direction:row;-webkit-
box-align:center;-ms-flex-align:center;align-items:center;padding-left:8px;padding-right:16px;min-height:40px;min-width:120px}.dropdown-menu__row:not(:first-child){border-top:dotted-] {+white;content:"";position:absolute;left:-7px;top:1px
}.open>.dropdown-menu__top-arrow{visibility:visible}.dropdown-menu__row{display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-orient:horizontal;-webkit-box-direction:normal;-ms-flex-direction:row;flex-direction:row;-webkit-box-
align:center;-ms-flex-align:center;align-items:center;padding-left:8px;padding-right:16px;min-height:40px;min-width:120px}.dropdown-menu__row:not(:first-child){border-top:dotted+} 1px #d3d3d3}
```

This appears to be just changing `#fff` to `white` in one file.

**Comment by nickstenning** [comment]
Looks like 4.4.0 is a bit *too* new, as x86_64 builds aren't even available yet! Going with 4.3.0 instead.

**Comment by robertknight** [comment]
This looks fine to me, except for whatever caused the [Jenkins build to fail](https://jenkins.hypothes.is/job/h/job/upgrade-sass/2/console). I can't reproduce the issue seen in that build myself locally with this branch.

**Comment by nickstenning** [comment]
Are you sure you can't? I can. Looks like a bug in libsass -- just trying to pin it down.

**Comment by nickstenning** [comment]
Looks like https://github.com/sass/libsass/issues/2260 to me.

**Comment by nickstenning** [comment]
Gah. 4.2.0 has the same problem. Looks like 4.4.0 will be released within the next few days and it seems to fix this so I'll mark this as WIP until then.

**Comment by nickstenning** [comment]
So, back to 4.4.0, and we'll kick off a new Travis build in a couple of days.

**Comment by nickstenning** [comment]
4.4.0 has now been properly released and appears to work.

**Comment by robertknight** [comment]
LGTM

**Pull request merged**
