### PR TITLE
Remove the new homepage feature

### PR DESCRIPTION
**Pull request by seanh**
Remove the new https://hypothes.is/ front page that was behind the
'new_homepage' feature flag, and all of the code that was added to
support it (and that isn't now also being used by something else).

### CODE REVIEW

**Comment by seanh** [comment]
@robertknight Is this what you wanted or did I rip out far too much?

**Comment by robertknight** [comment]
> @robertknight Is this what you wanted or did I rip out far too much?

I haven't tested the other site pages with this branch closely yet, but providing everything else still works then yes, this is fine. As @nickstenning said, we can get it back from version control if we need it.

**Comment by seanh** [comment]
I tested the other pages and all seemed fine but please do test yourself as well

**Comment by nickstenning** [comment]
LGTM.

**Pull request merged**
