### PR TITLE
Fix the Docker build

### PR DESCRIPTION
**Pull request by seanh**
TODO: Remove this workaround once
https://github.com/pyca/cryptography/issues/4264 is resolved.

crypotography (one of the dependencies that would be installed from our
requirements.txt file) currently has a problem building against LibreSSL
(LibreSSL is installed as a dependency of some of the apk packages we
install):

https://github.com/pyca/cryptography/issues/4264

So as a workaround install cryptography separately, building it against
OpenSSL, before LibreSSL gets installed.

### CODE REVIEW

**Comment by lyzadanger** [comment]
AFAICT, LGTM — hope this blows over quickly!

**Comment by seanh** [comment]
It looks like maybe there are two times the `cryptography` package gets installed. Once when building the docker image, and once when installing the test dependencies into tox's virtual environment. I think this [section of the `Jenkinsfile` that installs test dependencies](https://github.com/hypothesis/h/blob/887b9ef7c728e662107de136410c2c534adbef68/Jenkinsfile#L29-L43) is gonna need the same workaround as has been applied to the `Dockerfile`

**Comment by seanh** [comment]
Looking at the [Jenkins output from the failed build on master](https://jenkins.hypothes.is/job/h/job/master/1509/console) it kind of looks like building the hypothesis docker image actually succeeded (which is weird, because it didn't succeed locally for me or Rob) but then installing the test deps in tox failed (with the same crash as building the docker image was crashing with locally for me and Rob).

**Comment by seanh** [comment]
I still think the solution is that this [section of the `Jenkinsfile` that installs test dependencies](https://github.com/hypothesis/h/blob/887b9ef7c728e662107de136410c2c534adbef68/Jenkinsfile#L29-L43) is gonna need the same workaround as has been applied to the `Dockerfile`

**Comment by robertknight** [comment]
I have an alternative solution to consider. The only thing we use the `cryptography` library for is the HKDF key derivation function, for which there are alternative implementations. See https://github.com/hypothesis/h/pull/5056

**Pull request closed without merging**
