### PR TITLE
Show direct links on stream page when available

### PR DESCRIPTION
**Pull request by finitud**
Currently the links on the stream page point to the original annotated document. This pull request makes these links to be direct links to the annotation.

https://trello.com/c/iipUgujB/373-direct-link-to-annotation-from-stream-card-document-link

### CODE REVIEW

**Comment by nickstenning** [comment]
What's the status of this? Is it really WIP?

**Comment by finitud** [comment]
Yes, I'm refactoring some bits of code around this PR on @robertknight suggestion.

**Comment by nickstenning** [comment]
I'm going to close this PR. Please reopen against [hypothesis/client](https://github.com/hypothesis/client).

There are a couple of ways for you to move the PR. Here's one:

1. On this branch, run `git format-patch master`
2. Clone the new repository: `cd .. && git clone git@github.com:hypothesis/client.git`.
3. Copy all the `*.patch` files into the new repository: `cp h/*.patch client`
4. Change directory to the new repository: `cd client`
5. Checkout a new branch in the new repository: `git checkout -b my-branch-name`
6. Apply the patches to that branch by running `git am *.patch`

**Comment by finitud** [comment]
The changes are now being tracked at https://github.com/hypothesis/client/pull/1

**Pull request closed without merging**
