### PR TITLE
Apply the new design to the group create and join pages.

### PR DESCRIPTION
**Pull request by sheetaluk**
When the activity pages feature flag is enabled show the newly designed create and join group pages.

https://trello.com/c/Mpoggxop/426-style-group-pages-with-new-design-and-layout

### CODE REVIEW

**Comment by robertknight** [comment]
I've re-marked this as WIP because there are still `TODO` comments in the changes

**Comment by nickstenning** [comment]
It looks to me like there's still a piece missing from this form: the "Learn more about groups" link, but that doesn't block this merging.

**Comment by nickstenning** [comment]
Great! Note for the future, @sheetaluk: good to note stuff like that on the PR.

**Comment by sheetaluk** [comment]
Yes! I'm so sorry I forgot to.

**Pull request merged**
