### PR TITLE
Scroll share dialog into view when created

### LINKED ISSUE #3043: share button doesn't send me to share box
scrolling through annotations and then deciding to share the doc through the copy and pasteable via link activated by the share button.

clicking the share button jerks the sidebar but doesn't send me to that box, so i don't know if it's there unless i know to scroll up:

http://www.screencast.com/t/jGP1cNItMU4I

i've confirmed this to be a bug both using the extension in chrome and via in firefox.

### PR DESCRIPTION
**Pull request by robertknight**
This PR converts the `<share-dialog>` component from CoffeeScript to JS and updates the style for consistency with other components (first commit), and adds logic to scroll the dialog into view when it appears (second commit).

Fixes #3043

### CODE REVIEW

**Comment by robertknight** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;phJSNZgR&#x2F;315-bug-share-button-doesn-t-ensure-share-box-is-visible"> [BUG] Share button doesn&#39;t ensure share box is visible</a>

**Comment by seanh** [comment]
I found one UX issue (arguably):

1. Open the share dialog
2. Scroll in the sidebar so that the share dialog is out of view
3. Click the share button
4. It does not scroll the share dialog into view. What actually happens is that it closes the already-open share dialog.
5. Click the share button again, now it scrolls into view

Suggestion: clicking on the share button again when the share dialog is already open should not close the share dialog (that can be done with the x on the dialog itself). It _should_ scroll it into view if it isn't already in view. Else do nothing.

**Comment by seanh** [comment]
Code looks good, but let me know if you want to fix the above issue as part of this PR

**Comment by robertknight** [comment]
@seanh - Agreed, I have revised the second commit to implement the behavior you suggested.

**Comment by seanh** [comment]
Needs a rebase now.

I've re-tested and looks good.

By the way separate issue but it'd be nice to make the sign in card flash or something when you click the sign in button and the card is already shown and already in view

**Comment by nickstenning** [comment]
Rebased.

**Comment by nickstenning** [comment]
LGTM.

**Pull request merged**
