### PR TITLE
Fix document_uri unique constraint

### LINKED ISSUE #3480: document_uri unique constraint doesn't work as intended
The `document_uri` db table has `UNIQUE CONSTRAINT, btree (claimant_normalized, uri_normalized, type, content_type)` but neither `type` nor `content_type` have `NOT NULL` and `null` is not equal to `null` in PostgreSQL so you can insert multiple rows with the same `claimant_normalized`, `uri_normalized`, `type` and `content_type` as long as each row has `null` in either the `type` or `content_type` column (or both). These duplicate rows can either have the same or different `document_id`s. 

I think that duplicate rows like this can be created by concurrent requests because `find_or_create_by_uris()` creates `DocumentURI`s with `content_type = None`. And I guess if clients simply post `null` for the `type` and/or `content_type` in HTTP requests and make concurrent requests.

### PR DESCRIPTION
**Pull request by seanh**
Fixes #3480.

This pull request adds `NOT NULL` constraints and default values to the `type` and `content_type` columns of the `document_uri` table, thus making the unique constraint on that table work as intended.

Before this pull request it was possible for duplicate `document_uri` rows (same `claimant_normalized`, `uri_normalized`, `type` and `content_type`) to get into the db _if_ they had `null` in either the `type` or `content_type` columns or both, because `null` is not equal to `null` in PostgreSQL. I think that such rows _can_ actually be created by our code when there are concurrent requests.

I haven't checked whether we actually have any such duplicate rows in our production database but even if we don't some could be added at any time and then attempting to deploy this db migration would crash.

So I've written this migration script to deduplicate the `document_uri` table before adding the constraints to it. When there are groups of duplicate rows it deletes all but the most recently updated row.

Note that these duplicate rows could all point to the same or to different `document` rows, so this deduplication may leave behind `document` rows with no corresponding `document_uri`s.

This pull request is done as two separate commits to enable testing.

I've tested this migration script in two ways.

First way - checkout <https://github.com/hypothesis/h/commit/d2983d3113e69028f9aa5d277e841719660c1cc6> and run [the tests in that commit](https://github.com/hypothesis/h/blob/d2983d3113e69028f9aa5d277e841719660c1cc6/tests/h/migrations/versions/fix_document_uri_unique_constraint_test.py):

```
$ git checkout d2983d3113e69028f9aa5d277e841719660c1cc6
$ py.test tests/h/migrations/versions/fix_document_uri_unique_constraint_test.py
==================== test session starts ======================================
platform linux2 -- Python 2.7.11+, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/seanh/Projects/hypothesis/h, inifile: tox.ini
plugins: robpol86-pytest-ipdb-0.0.1, hypothesis-3.4.0, profiling-1.1.1
collected 1 items

tests/h/migrations/versions/fix_document_uri_unique_constraint_test.py .

============= 1 passed in 1.02 seconds ========================================
```

Second way:

- Starting with a dev db schema from master
- checkout <https://github.com/hypothesis/h/commit/d2983d3113e69028f9aa5d277e841719660c1cc6> again
- Run `pshell` and import and run the [add_test_data() function from that commit](https://github.com/hypothesis/h/blob/d2983d3113e69028f9aa5d277e841719660c1cc6/tests/h/migrations/versions/fix_document_uri_unique_constraint_test.py#L7)
  against the dev db, adding the test data to the dev db
- Run `psql` and verify that the test data was inserted
- Checkout this branch and run the migration script with `alembic`
- Run `psql` again and check that both the schema and the data look right

```
$ git checkout master
Previous HEAD position was d2983d3... Add migration script to fix document_uri unique constraint
Switched to branch 'master'

$ # Reset the database to as it is on master.
$ docker rm -f postgres; and docker run -d --name postgres -p 5432:5432 postgres; and sleep 5; and docker run -it --link postgres:postgres --rm postgres sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres -c "CREATE DATABASE htest;"'
postgres
76dc39e71dab3b672b35aaa90a4fce09124444ccda64b74eb6fc290984308659
CREATE DATABASE

$ # Run h to create the database.
$ set -x MODEL_CREATE_ALL true
$ gunicorn --reload --paste conf/development-app.ini
2016-06-17 15:30:21,127 [22086] [gunicorn.error:INFO] Starting gunicorn 19.6.0
2016-06-17 15:30:21,128 [22086] [gunicorn.error:INFO] Listening at: http://127.0.0.1:5000 (22086)
2016-06-17 15:30:21,128 [22086] [gunicorn.error:INFO] Using worker: sync
2016-06-17 15:30:21,130 [22093] [gunicorn.error:INFO] Booting worker with pid: 22093
^C2016-06-17 15:30:23,820 [22086] [gunicorn.error:INFO] Handling signal: int
2016-06-17 15:30:23,820 [22086] [gunicorn.error:INFO] Shutting down: Master

$ git checkout d2983d3113e69028f9aa5d277e841719660c1cc6
Note: checking out 'd2983d3113e69028f9aa5d277e841719660c1cc6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d2983d3... Add migration script to fix document_uri unique constraint

$ # At this point the database does not contain the new NOT NULL constraints.
$ pgcli postgresql://postgres@localhost/postgres
Version: 0.20.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
postgres> \d document_uri
+---------------------+-----------------------------+------------------------------------------------------------+
| Column              | Type                        | Modifiers                                                  |
|---------------------+-----------------------------+------------------------------------------------------------|
| created             | timestamp without time zone |  not null default now()                                    |
| updated             | timestamp without time zone |  not null default now()                                    |
| id                  | integer                     |  not null default nextval('document_uri_id_seq'::regclass) |
| claimant            | text                        |  not null                                                  |
| claimant_normalized | text                        |  not null                                                  |
| uri                 | text                        |  not null                                                  |
| uri_normalized      | text                        |  not null                                                  |
| type                | text                        |                                                            |
| content_type        | text                        |                                                            |
| document_id         | integer                     |  not null                                                  |
+---------------------+-----------------------------+------------------------------------------------------------+
Indexes:
    "pk__document_uri" PRIMARY KEY, btree (id)
    "uq__document_uri__claimant_normalized" UNIQUE CONSTRAINT, btree (claimant_normalized, uri_normalized, type, content_type)
    "ix__document_uri_document_id" btree (document_id)
    "ix__document_uri_updated" btree (updated)
    "ix__document_uri_uri_normalized" btree (uri_normalized)
Foreign-key constraints:
    "fk__document_uri__document_id__document" FOREIGN KEY (document_id) REFERENCES document(id)

Time: 0.021s
postgres>
Goodbye!

$ # Add the test data to the dev db.
$ pshell conf/development-app.ini
Environment:
  app          The WSGI application.
  registry     Active Pyramid registry.
  request      Active request object.
  root         Root of the default resource tree.
  root_factory Default root factory used to create `root`.

>>> from tests.h.migrations.versions.fix_document_uri_unique_constraint_test import add_test_data
>>> from h import db
>>> add_test_data(db.Session)
([<DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI
 None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>], [<DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <Doc
umentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>, <DocumentURI None>])
>>> import transaction
>>> transaction.commit()
>>>
$ pgcli postgresql://postgres@localhost/postgres
Version: 0.20.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
postgres> SELECT * FROM document_uri;
+----------------------------+----------------------------+------+-----------------------+-----------------------+-----------------------+-----------------------+---------+-----------------+---------------+
| created                    | updated                    |   id | claimant              | claimant_normalized   | uri                   | uri_normalized        | type    | content_type    |   document_id |
|----------------------------+----------------------------+------+-----------------------+-----------------------+-----------------------+-----------------------+---------+-----------------+---------------|
| 2016-06-17 14:31:20.875973 | 2016-06-17 14:31:20.875980 |    1 | http://example.com/1  | http://example.com/1  | http://example.com/1  | http://example.com/1  | type_1  | content_type_1  |             1 |
| 2016-06-17 14:31:20.877511 | 2016-06-17 14:31:20.877518 |    2 | http://example.com/2  | http://example.com/2  | http://example.com/2  | http://example.com/2  | type_2  | content_type_2  |             1 |
| 2016-06-17 14:31:20.878234 | 2016-06-17 14:31:20.878241 |    3 | http://example.com/3  | http://example.com/3  | http://example.com/3  | http://example.com/3  | <null>  | content_type_3  |             1 |
| 2016-06-17 14:31:20.878852 | 2016-06-17 14:31:20.878859 |    4 | http://example.com/4  | http://example.com/4  | http://example.com/4  | http://example.com/4  | <null>  | content_type_4  |             1 |
| 2016-06-17 14:31:20.879454 | 2016-06-17 14:31:20.879459 |    5 | http://example.com/5  | http://example.com/5  | http://example.com/5  | http://example.com/5  | type_5  | <null>          |             1 |
| 2016-06-17 14:31:20.880049 | 2016-06-17 14:31:20.880055 |    6 | http://example.com/6  | http://example.com/6  | http://example.com/6  | http://example.com/6  | type_6  | <null>          |             1 |
| 2016-06-17 14:31:20.880536 | 2016-06-17 14:31:20.880541 |    7 | http://example.com/7  | http://example.com/7  | http://example.com/7  | http://example.com/7  | <null>  | content_type_7  |             1 |
| 2016-06-17 14:31:20.880969 | 2016-06-17 14:31:20.880974 |    8 | http://example.com/7  | http://example.com/7  | http://example.com/7  | http://example.com/7  | <null>  | content_type_7  |             1 |
| 2016-06-17 14:31:20.881413 | 2016-06-17 14:31:20.881419 |    9 | http://example.com/7  | http://example.com/7  | http://example.com/7  | http://example.com/7  | <null>  | content_type_7  |             1 |
| 2016-06-17 14:31:20.881828 | 2016-06-17 14:31:20.881833 |   10 | http://example.com/8  | http://example.com/8  | http://example.com/8  | http://example.com/8  | type_8  | <null>          |             1 |
| 2016-06-17 14:31:20.882240 | 2016-06-17 14:31:20.882245 |   11 | http://example.com/8  | http://example.com/8  | http://example.com/8  | http://example.com/8  | type_8  | <null>          |             1 |
| 2016-06-17 14:31:20.882639 | 2016-06-17 14:31:20.882644 |   12 | http://example.com/8  | http://example.com/8  | http://example.com/8  | http://example.com/8  | type_8  | <null>          |             1 |
| 2016-06-17 14:31:20.883035 | 2016-06-17 14:31:20.883040 |   13 | http://example.com/9  | http://example.com/9  | http://example.com/9  | http://example.com/9  | <null>  | <null>          |             1 |
| 2016-06-17 14:31:20.883442 | 2016-06-17 14:31:20.883447 |   14 | http://example.com/9  | http://example.com/9  | http://example.com/9  | http://example.com/9  | <null>  | <null>          |             1 |
| 2016-06-17 14:31:20.883888 | 2016-06-17 14:31:20.883893 |   15 | http://example.com/9  | http://example.com/9  | http://example.com/9  | http://example.com/9  | <null>  | <null>          |             1 |
| 2016-06-17 14:31:20.884313 | 2016-06-17 14:31:20.884318 |   16 | http://example.com/10 | http://example.com/10 | http://example.com/10 | http://example.com/10 | <null>  | content_type_10 |             1 |
| 2016-06-17 14:31:20.884792 | 2016-06-17 14:31:20.884797 |   17 | http://example.com/10 | http://example.com/10 | http://example.com/10 | http://example.com/10 | type_10 | <null>          |             1 |
| 2016-06-17 14:31:20.885244 | 2016-06-17 14:31:20.885249 |   18 | http://example.com/10 | http://example.com/10 | http://example.com/10 | http://example.com/10 | <null>  | <null>          |             1 |
+----------------------------+----------------------------+------+-----------------------+-----------------------+-----------------------+-----------------------+---------+-----------------+---------------+
SELECT 18
Time: 0.023s
postgres>
Goodbye!

$ git checkout 3480-fix-document-uri-unique-constraint
Previous HEAD position was d2983d3... Add migration script to fix document_uri unique constraint
Switched to branch '3480-fix-document-uri-unique-constraint'
$ alembic -c conf/alembic.ini stamp 296573bb30b3
2016-06-17 15:31:56 22480 alembic.runtime.migration [INFO] Context impl PostgresqlImpl.
2016-06-17 15:31:56 22480 alembic.runtime.migration [INFO] Will assume transactional DDL.
2016-06-17 15:31:56 22480 alembic.runtime.migration [INFO] Running stamp_revision  -> 296573bb30b3
$ alembic -c conf/alembic.ini upgrade +1
2016-06-17 15:32:01 22532 alembic.runtime.migration [INFO] Context impl PostgresqlImpl.
2016-06-17 15:32:01 22532 alembic.runtime.migration [INFO] Will assume transactional DDL.
2016-06-17 15:32:01 22532 alembic.runtime.migration [INFO] Running upgrade 296573bb30b3 -> 467ea2898660, Fix document_uri unique constraint.
/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value ''. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
$ pgcli postgresql://postgres@localhost/postgres
Version: 0.20.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
postgres> \d document_uri
+---------------------+-----------------------------+------------------------------------------------------------+
| Column              | Type                        | Modifiers                                                  |
|---------------------+-----------------------------+------------------------------------------------------------|
| created             | timestamp without time zone |  not null default now()                                    |
| updated             | timestamp without time zone |  not null default now()                                    |
| id                  | integer                     |  not null default nextval('document_uri_id_seq'::regclass) |
| claimant            | text                        |  not null                                                  |
| claimant_normalized | text                        |  not null                                                  |
| uri                 | text                        |  not null                                                  |
| uri_normalized      | text                        |  not null                                                  |
| type                | text                        |  not null default ''::text                                 |
| content_type        | text                        |  not null default ''::text                                 |
| document_id         | integer                     |  not null                                                  |
+---------------------+-----------------------------+------------------------------------------------------------+
Indexes:
    "pk__document_uri" PRIMARY KEY, btree (id)
    "uq__document_uri__claimant_normalized" UNIQUE CONSTRAINT, btree (claimant_normalized, uri_normalized, type, content_type)
    "ix__document_uri_document_id" btree (document_id)
    "ix__document_uri_updated" btree (updated)
    "ix__document_uri_uri_normalized" btree (uri_normalized)
Foreign-key constraints:
    "fk__document_uri__document_id__document" FOREIGN KEY (document_id) REFERENCES document(id)

Time: 0.021s
postgres> SELECT * FROM document_uri;
+----------------------------+----------------------------+------+-----------------------+-----------------------+-----------------------+-----------------------+---------+-----------------+---------------+
| created                    | updated                    |   id | claimant              | claimant_normalized   | uri                   | uri_normalized        | type    | content_type    |   document_id |
|----------------------------+----------------------------+------+-----------------------+-----------------------+-----------------------+-----------------------+---------+-----------------+---------------|
| 2016-06-17 14:31:20.875973 | 2016-06-17 14:31:20.875980 |    1 | http://example.com/1  | http://example.com/1  | http://example.com/1  | http://example.com/1  | type_1  | content_type_1  |             1 |
| 2016-06-17 14:31:20.877511 | 2016-06-17 14:31:20.877518 |    2 | http://example.com/2  | http://example.com/2  | http://example.com/2  | http://example.com/2  | type_2  | content_type_2  |             1 |
| 2016-06-17 14:31:20.878234 | 2016-06-17 14:31:20.878241 |    3 | http://example.com/3  | http://example.com/3  | http://example.com/3  | http://example.com/3  |         | content_type_3  |             1 |
| 2016-06-17 14:31:20.878852 | 2016-06-17 14:31:20.878859 |    4 | http://example.com/4  | http://example.com/4  | http://example.com/4  | http://example.com/4  |         | content_type_4  |             1 |
| 2016-06-17 14:31:20.881413 | 2016-06-17 14:31:20.881419 |    9 | http://example.com/7  | http://example.com/7  | http://example.com/7  | http://example.com/7  |         | content_type_7  |             1 |
| 2016-06-17 14:31:20.884313 | 2016-06-17 14:31:20.884318 |   16 | http://example.com/10 | http://example.com/10 | http://example.com/10 | http://example.com/10 |         | content_type_10 |             1 |
| 2016-06-17 14:31:20.879454 | 2016-06-17 14:31:20.879459 |    5 | http://example.com/5  | http://example.com/5  | http://example.com/5  | http://example.com/5  | type_5  |                 |             1 |
| 2016-06-17 14:31:20.880049 | 2016-06-17 14:31:20.880055 |    6 | http://example.com/6  | http://example.com/6  | http://example.com/6  | http://example.com/6  | type_6  |                 |             1 |
| 2016-06-17 14:31:20.882639 | 2016-06-17 14:31:20.882644 |   12 | http://example.com/8  | http://example.com/8  | http://example.com/8  | http://example.com/8  | type_8  |                 |             1 |
| 2016-06-17 14:31:20.884792 | 2016-06-17 14:31:20.884797 |   17 | http://example.com/10 | http://example.com/10 | http://example.com/10 | http://example.com/10 | type_10 |                 |             1 |
| 2016-06-17 14:31:20.883888 | 2016-06-17 14:31:20.883893 |   15 | http://example.com/9  | http://example.com/9  | http://example.com/9  | http://example.com/9  |         |                 |             1 |
| 2016-06-17 14:31:20.885244 | 2016-06-17 14:31:20.885249 |   18 | http://example.com/10 | http://example.com/10 | http://example.com/10 | http://example.com/10 |         |                 |             1 |
+----------------------------+----------------------------+------+-----------------------+-----------------------+-----------------------+-----------------------+---------+-----------------+---------------+
SELECT 12
Time: 0.017s
postgres>
Goodbye!

$ alembic -c conf/alembic.ini downgrade -1
2016-06-17 15:32:49 22717 alembic.runtime.migration [INFO] Context impl PostgresqlImpl.
2016-06-17 15:32:49 22717 alembic.runtime.migration [INFO] Will assume transactional DDL.
2016-06-17 15:32:49 22717 alembic.runtime.migration [INFO] Running downgrade 467ea2898660 -> 296573bb30b3, Fix document_uri unique constraint.
$ alembic -c conf/alembic.ini upgrade +1
2016-06-17 15:32:53 22766 alembic.runtime.migration [INFO] Context impl PostgresqlImpl.
2016-06-17 15:32:53 22766 alembic.runtime.migration [INFO] Will assume transactional DDL.
2016-06-17 15:32:53 22766 alembic.runtime.migration [INFO] Running upgrade 296573bb30b3 -> 467ea2898660, Fix document_uri unique constraint.
/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value ''. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
```

I've also added [tests for the new db schema when adding new data](https://github.com/hypothesis/h/blob/0f96e8f6c892cb0c0d59e5073e584ce2195ff5e4/tests/h/api/models/document_test.py#L170)

### CODE REVIEW

**Comment by seanh** [comment]
Marked this as WIP again because I'm now getting `ConcurrentUpdateError` (not caught by `pyramid_tm`) when creating annotations on this branch (doesn't happen on master)...

**Comment by seanh** [comment]
https://github.com/hypothesis/h/pull/3495/commits/751520f6a786efac6c247212ba583572d8257a04 is a preliminary fix for the crash when creating new annotations, but I want to investigate a little more

**Comment by seanh** [comment]
https://github.com/hypothesis/h/pull/3495/commits/484fe24f0e65d7e70cd07c5a5e2a24a0772b2f84 is a finished fix for the problem, removing wip

**Comment by nickstenning** [comment]
LGTM.

**Pull request merged**
