### PR TITLE
Make email optional in POST /api/users

### PR DESCRIPTION
**Pull request by seanh**
Depends on <https://github.com/hypothesis/h/pull/5103>.

### CODE REVIEW

**Comment by seanh** [comment]
The tests will be failing because of the unmerged PR this depends on. There's at least one now-invalid test that is failing and needs to be deleted too.

I'm a little suspicious of how easily this worked, and that it didn't require any changes to the `UserSignup` service for example, reminder to self to investigate further.

**Comment by lyzadanger** [comment]
Hi, @seanh! What do you think of maintaining the `email` requirement in certain circumstances, e.g.:

* For first-party users
* If identity information—the support for which we haven't added yet—is not present

That is, maybe we could hold off on making `email` optional at the API level at this step? Happy to chat about this with you!

**Comment by seanh** [comment]
Aside from possibly being more restrictive about who is allowed to create users without emails, this is ready for review now.

**Comment by lyzadanger** [comment]
Hi, @seanh .... Maybe we could wait on this until we define the updated API surface for this endpoint (integrating identities)? I have a hunch we may wish to require email unless there's 1 or more identities for a user.

**Comment by lyzadanger** [comment]
This was handled in https://github.com/hypothesis/h/pull/5169

**Pull request closed without merging**
