### PR TITLE
Raise HTTPConflict (409) when email uniqueness constraint violated

### PR DESCRIPTION
**Pull request by lyzadanger**
This PR is based on https://github.com/hypothesis/h/pull/4945 — the only difference is the addition of a few tests and a recent rebase on `master`.

These changes will cause a 409 HTTP response code if one tries to update a user's email address to a value already in use by another record. This situation passes validation but fails DB integrity checking.

Further work to be done on returning consistent HTTP response codes, but this is a nice improvement, I think!

Thanks to @jmcarp for this work!

### CODE REVIEW

**Comment by lyzadanger** [comment]
@seanh Could I get your blessing on the tests I added to this PR?

**Comment by lyzadanger** [comment]
> LGTM. I wonder if there are any other situations which ought to report the same status?

Absolutely. I plan to start attacking a few of those in the next weeks.

**Comment by robertknight** [comment]
Taking a look at some of the surrounding code I see that we raise `ValidationError` for similar issues in the API request for _creating_ user accounts. IMO `HTTPConflict` is "more correct" because an email/username is syntactically valid if it conflicts with an existing user, and an HTTP 429 status is more informative that say a generic HTTP 400. It would be good to make these consistent though.

**Comment by lyzadanger** [comment]
> Taking a look at some of the surrounding code I see that we raise ValidationError for similar issues in the API request for creating user accounts. IMO HTTPConflict is "more correct" because an email/username is syntactically valid if it conflicts with an existing user, and an HTTP 429 status is more informative that say a generic HTTP 400. It would be good to make these consistent though.

I agree; I consider that subsequent work!

**Pull request merged**
