### PR TITLE
Upgrade to Pyramid 1.7

### PR DESCRIPTION
**Pull request by nickstenning**
This PR upgrades us to the latest version of Pyramid.

As of Pyramid 1.7, checking a CSRF token supplied in a GET parameter is not supported[1]. This is fine, as the client already supplies the CSRF token in the X-CSRF-Token request header anyway.

See also: https://github.com/hypothesis/client/pull/89

[1]: http://docs.pylonsproject.org/projects/pyramid/en/latest/whatsnew-1.7.html#backwards-incompatibilities

### CODE REVIEW

**Comment by chdorner** [comment]
Marking as WIP as @nickstenning found some issues that need to be worked out first (https://hypothes-is.slack.com/archives/public/p1473238382000518).

**Comment by chdorner** [comment]
We should probably wait until Monday to get as many people as possible updating the extension to v0.40.0.

**Comment by nickstenning** [comment]
```
ubuntu@app-1:~$ sudo fgrep -c '/api/token' /var/log/nginx/access.log.1
34393
ubuntu@app-1:~$ sudo fgrep '/api/token' /var/log/nginx/access.log.1 | fgrep -c assertion
122
```

122 / 34,393 ≈ 0.35%

I'd say we're safe to merge this now.

**Comment by chdorner** [comment]
LGTM. I'll put this out on staging and maybe we can leave it there for a day or so.

**Pull request merged**
