### PR TITLE
Open Graph protocol metadata added to Annotation view

### PR DESCRIPTION
**Pull request by BigBlueHat**
http://ogp.me/ basic implementation for better
display of content if shared via social network
sites that support OGP (most do).

I completely believe this could probably use some improvement. :smiley_cat: Let me know how. :wink:

For instance `layout.meta_properties` and `layout.meta_attrs` could be merged into a more complex template...this was just faster/simpler and showed of the intention.

### CODE REVIEW

**Comment by tilgovi** [comment]
Great to open for discussion.

If you're going to modify the base template thought I don't see why we shouldn't just use some renderer globals like I had in f9a192f9ca49d57d219858da4461e730680366ce. That was written where each could be a list of dictionaries that say arbitrary attributes.

@aron?

**Comment by BigBlueHat** [comment]
@tilgovi that would be ideal as who knows what else could be (or will be) crammed into those two extension points over the years.

**Comment by aron** [comment]
@tilgovi yeah that sounds good to me, where would these be defined in this case though?

**Comment by aron** [comment]
Okay, I updated this so that `link_attrs` and `meta_attrs` now accept a list of dicts. That's a much better api. I've also removed the dependence on layout as that is process and not request specific. So it makes sense to keep it in the views.

I looked into using the Jinja2 globals object but couldn't get access to it in the view, it's on `config.get_jinja2_environment()`. And as for the moment we only set these attributes in the view, it makes sense to just return them there.

**Comment by csillag** [comment]
> http://ogp.me/ basic implementation for better display of content if shared via social network sites that support OGP (most do).

Nice!

Hint: we also have an issue for producing embeddable annotation cards - see https://github.com/hypothesis/h/issues/141.

**Comment by nickstenning** [comment]
LGTM.

**Comment by BigBlueHat** [comment]
@aron great work!

@csillag #141 is precisely why this happened. :wink: ...and 'cause I wantz it. :smile_cat:

**Comment by csillag** [comment]
> @csillag #141 is precisely why this happened. :wink:

Good to hear that.
(Relieved to experience some synchronicity in thinking, once in a while :) )

**Pull request merged**
