### PR TITLE
Add the concept of "staff member" users

### PR DESCRIPTION
**Pull request by seanh**
And enabling features for staff members only

### CODE REVIEW

**Comment by seanh** [comment]
Needs tests.

Currently a lot of duplication between this and the admins feature.

**Comment by seanh** [comment]
@nickstenning

**Comment by tilgovi** [comment]
Rebased over the AdminResource stuff

**Comment by nickstenning** [comment]
N.B. for the future -- if a PR includes a migration, it's worth checking that the migration doesn't introduce a branchpoint, and if it does, rebase the branch so as to identify the correct migration path before merging.

Fixed by https://github.com/hypothesis/h/commit/e78c1939ca20b58f7c6b4753362c4bc30cbe7ea7.

**Pull request merged**
