### PR TITLE
Refactor User.get_by_id()

### PR DESCRIPTION
**Pull request by seanh**
- Take domain arg instead of request
- Use util.split_user(), remove code duplication
- Remove unused capability to get a user by integer primary key
- Also fix some variable names in split_user()

### CODE REVIEW

**Comment by tilgovi** [comment]
Still think it should be `get_by_uri` or something that doesn't seem like it's a primary integer key lookup.

**Comment by tilgovi** [comment]
Also, I find passing the domain in and then comparing it a little bit weird. How many places do we even call this, I wonder?

**Comment by tilgovi** [comment]
There are several, to answer my own question.

We have had before, and could have again, simply a `user` property on the request. That property function could do `split_user` then compare to domain then return `None` or lookup by username.

Then, many of the places where we are doing `get_by_userid` might just become `request.user`?

**Comment by seanh** [comment]
> Still think it should be get_by_uri or something that doesn't seem like it's a primary integer key lookup.

We consistently call these things `userid`s throughout the codebase. `get_by_userid()`?

> Also, I find passing the domain in and then comparing it a little bit weird. How many places do we even call this, I wonder?

It's bizarre, but it's what the current code does (just much less clearly). Didn't you object to me removing this check in <https://github.com/hypothesis/h/pull/2433>?

> We have had before, and could have again, simply a user property on the request. That property function could do split_user then compare to domain then return None or lookup by username.
> 
> Then, many of the places where we are doing get_by_userid might just become request.user?

I don't think  that `get_by_id()` is always used to get the authorized user though, so it might not replace all uses.

**Comment by tilgovi** [comment]
I hear you on all of it. Let's do `get_by_userid`.

**Comment by tilgovi** [comment]
Rename the function and feel free to merge it yourself. Everything else is fine.

**Comment by tilgovi** [comment]
Okay, I'm going to merge this and do a consistency refactor.

**Pull request merged**
